/**
 * The Quiet Under Blackstone: the first written campaign, and the worked
 * example of the format (CAMPAIGN_TEMPLATE.md is the same fields, blank).
 *
 * Fantasy, three acts, one character between levels 1 and 3, built only
 * from creatures the rules engine has numbers for (goblins, skeletons) and
 * NPC tokens the roster draws. Every encounter's failure assumes the
 * character went down and lived: goblins take prisoners and the dead drag
 * the fallen to their master. The death saves are still the dice's.
 *
 * The map, in cells (north is up, cy-1):
 *
 *            cx -1          cx 0              cx 1
 *   cy -4                   king's tomb
 *   cy -3    the cairn      barrow halls      lower mine (Deep Door)
 *   cy -2    barrow-field   goblin camp       upper mine
 *   cy -1    barrow-field   old mine road
 *   cy  0    shrine         the square        mayor's house
 *   cy  1                   carter's yard
 *
 * Ids are permanent once this has been played (see campaign/types.ts).
 */
import type { CampaignModule } from "../types";

export const BLACKSTONE: CampaignModule = {
  id: "blackstone",
  version: 2,
  template: "fantasy",

  premise: {
    title: "The Quiet Under Blackstone",
    tone: "Folk horror with a warm centre: dread at night, small kindnesses by day, and nobody simply evil, the villain included.",
    setting:
      "Blackstone, a played-out silver-mining village of about sixty, four days up a cold valley from the nearest town. Above it: a ridge of royal barrows, and the old mine, held for three generations by goblins under an oath the village never talks about.",
    centralConflict:
      "A grieving scholar is waking the dead king under the ridge to use his crown, and Blackstone's mayor has been selling him the grave-silver to do it, not knowing what for.",
    hook: "Three people have vanished from Blackstone in two weeks, and the village says the goblins took them. The mayor is offering a reward. Up on the ridge, at night, something walks that is not a goblin.",
    bigQuestion: "Who is waking the dead under Blackstone, and what does he want them for?",
    endState: {
      success: "The king sleeps again, the scholar is stopped or lets go, the goblins and the village swear a new oath, Tam goes home, and Blackstone sees the spring.",
      failure: "The Ember Crown is lit, King Orrin wakes, every grave on the ridge empties, and the dead walk down the valley road. Blackstone is the first village they reach.",
    },
  },

  start: {
    location: "loc_square",
    situation:
      "Dusk. A fresh notice by the well names the third missing person, Tam Holt. Mayor Venn reads it to a small, angry crowd and promises a reward to whoever brings the goblins to heel. The player has just walked in on the valley road.",
  },

  truths: [
    {
      id: "t_three_missing",
      visibility: "known",
      text: "Three villagers have vanished in two weeks: Bessa Crane, the miller's daughter; old Jory Flint, a retired miner; and Tam Holt, the carter's fifteen-year-old son.",
    },
    {
      id: "t_goblins_near",
      visibility: "known",
      text: "A goblin clan, the Hollow Teeth, lives in the old mine above the village and has for longer than anyone remembers. Villagers rarely see them.",
    },
    {
      id: "t_mine_played_out",
      visibility: "known",
      text: "The mine's silver ran out a year ago, and the village has been getting poorer since.",
    },
    {
      id: "t_barrow_field",
      visibility: "known",
      text: "The ridge is the barrow-field, graves of the kings of a kingdom that fell centuries ago. Nobody goes up; children are told pointing at it is bad luck.",
    },
    {
      id: "t_grain_toll",
      visibility: "discoverable",
      text: "Since its founding the village has paid the Hollow Teeth a grain toll each season for guarding the bottom of the mine. Mayor Venn stopped paying three months ago, to save money.",
      learnedVia: ["the tithe ledger in the mayor's study", "Grukka or any Hollow Teeth goblin", "Sexton Pell, who remembers the old terms", "Wenna Holt, who used to haul the grain"],
    },
    {
      id: "t_goblins_took_two",
      visibility: "discoverable",
      text: "The Hollow Teeth took Bessa and Jory as surety for the unpaid toll. Both are alive, fed, unhurt and bored, roped under an awning in the goblin camp.",
      learnedVia: ["the tracks from the mill up the mine road", "the goblin camp itself", "Grukka", "a captured or befriended goblin"],
    },
    {
      id: "t_mayor_selling_silver",
      visibility: "discoverable",
      text: "Venn sells grave-silver to a buyer he has never met. His men dug it from the bottom of the mine, where the workings broke into old barrow tunnels; Wenna carts it to the cairn on the ridge, where the buyer leaves old royal coin.",
      learnedVia: ["the buyer's letters in the mayor's locked desk", "Wenna Holt", "Grukka, whose goblins watched the digging", "the picks and weight ledger left in the lower mine"],
      sets: ["evidence_against_mayor"],
    },
    {
      id: "t_dead_walk_ridge",
      visibility: "discoverable",
      text: "Skeletons walk the barrow-field at night. They do not come down into the village. Yet.",
      learnedVia: ["watching the ridge after dark", "Hobb the watchman, who has seen them twice and told nobody", "Sexton Pell"],
    },
    {
      id: "t_lantern_mark",
      visibility: "discoverable",
      text: "The buyer signs every letter with a small drawn lantern and collects the silver from the cairn at midnight.",
      learnedVia: ["the buyer's letters", "Wenna Holt", "watching the cairn at night"],
    },
    {
      id: "t_tam_below",
      visibility: "discoverable",
      text: "Goblins did not take Tam. Curious about his mother's heavy crates, he went down the mine alone; the dead took him to the Lamplighter, who keeps him entranced as a lamp-bearer. He is alive.",
      learnedVia: ["Grukka, whose sentries saw him go down", "a boy's boot prints by the Deep Door", "a glimpse of a boy with a lantern pole among the dead", "finding him in the barrow halls"],
    },
    {
      id: "t_oath_seal",
      visibility: "discoverable",
      text: "The oath was never about the mine. The Hollow Teeth keep the Deep Door shut: the stone seal between the mine's bottom and the barrow halls, so nothing buried there comes down into the valley. The grain was their wage, sworn long ago to the keepers of the Quiet Bell.",
      learnedVia: ["Sexton Pell", "Grukka, once she trusts the player", "the carvings on the Deep Door", "the oath stone in the goblin camp"],
    },
    {
      id: "t_silver_given",
      visibility: "discoverable",
      text: "Grave-silver only holds the Lamplighter's cold flame if living hands give it; stolen, it will not burn. That is why he buys it, and why cutting off the mayor's silver slows him.",
      learnedVia: ["Sexton Pell", "Corvane's journal", "studying the Grave Lantern (Arcana)"],
    },
    {
      id: "t_corvane_is_buyer",
      visibility: "secret",
      text: "The buyer is Corvane Ash, a royal archivist from the capital who left in disgrace. He is the Lamplighter, and the ridge's dead answer to his Grave Lantern.",
      learnedVia: ["meeting him at the cairn", "the scratched-out archive seal on his payment purse", "Tam, once woken", "Corvane himself"],
      revealWhen: { allOf: ["act:act_silver_road"] },
    },
    {
      id: "t_corvane_daughter",
      visibility: "secret",
      text: "Corvane's daughter Lise died of a winter fever two years ago while he was away in the archives. He believes the Ember Crown, which commands the dead, can call her back. It cannot: it calls back the body, never the person.",
      learnedVia: ["Corvane's journal in the barrow halls", "Tam, half-woken", "Corvane himself, if the player earns his trust", "Sexton Pell, who knows what the crown does"],
      revealWhen: { allOf: ["t_corvane_is_buyer"] },
    },
    {
      id: "t_crown_price",
      visibility: "secret",
      text: "The Ember Crown's wearer commands the dead and slowly becomes one: it takes their warmth until they are the next unburied king.",
      learnedVia: ["the inscription on King Orrin's tomb", "the Deep Door carvings, read in full", "Sexton Pell's grandmother's account", "King Orrin himself, if he wakes"],
      revealWhen: { anyOf: ["act:act_silver_road", "act:act_unburied_king"] },
    },
    {
      id: "t_bell_rite",
      visibility: "secret",
      text: "The Quiet Bell, a fist-sized bronze hand bell over the shrine's altar that everyone takes for decoration, was cast to lay King Orrin to rest. Rung in his tomb, it puts every dead thing in the barrow back to sleep, and its sound breaks the Lamplighter's hold on Tam.",
      learnedVia: ["Sexton Pell, once she trusts the player", "the bell's own inscription, read with Religion"],
      revealWhen: { anyOf: ["pell_trusts_player", "cl_bell_inscription"] },
    },
  ],

  villain: {
    npc: "npc_corvane",
    goal: "Light the Ember Crown on King Orrin's head and use its command over the dead to call his daughter Lise back.",
    motivation: "Grief and guilt: Lise died while he was away chasing a footnote, and he has not forgiven himself one day since.",
    plan: "Buy grave-silver from the mayor, forge the Grave Lantern from it, raise the barrow's dead with its light, wake King Orrin in his tomb, and light the crown.",
    resources: ["the Grave Lantern, nearly finished", "the barrow-field's skeletons", "Tam Holt, entranced, as lamp-bearer", "a purse of old royal coin", "two years of study of this one rite"],
    allies: ["the dead, through the lantern", "Mayor Venn, unknowing"],
    weakness: "The Grave Lantern. Without it the dead stop obeying and he is a frail man alone in a cold tomb. It can be smashed, snuffed, or drowned out by the Quiet Bell.",
    limitations: [
      "no fighter; avoids being seen",
      "the dead obey the lantern, not him, and cannot leave the barrow-field or the halls while the Deep Door holds",
      "the lantern burns only on silver living hands give, and the mayor's is the last in the valley",
    ],
    status: "Living in the barrow halls, coming up through the cairn at midnight for the mayor's silver. The lantern is nearly finished.",
    clock: [
      {
        id: "c_ridge_walkers",
        when: { afterScene: 12 },
        event: "A shepherd sees two skeletons on the barrow-field at dusk and runs into the village screaming. Blackstone blames goblin witchcraft, and talk turns to raiding the mine.",
        sets: ["village_wants_raid"],
      },
      {
        id: "c_lantern_finished",
        when: { afterScene: 30 },
        preventedBy: { anyOf: ["silver_cut_off"] },
        event: "Corvane finishes the Grave Lantern with the last of the mayor's silver. Its cold light wakes every grave on the ridge, and the dead gather in the barrow halls.",
        sets: ["lantern_finished"],
      },
      {
        id: "c_silver_taken",
        when: { allOf: ["prevented:c_lantern_finished"], afterScene: 42 },
        preventedBy: { anyOf: ["corvane_stopped", "lantern_destroyed"] },
        event: "Starved of silver, Corvane comes down into Blackstone one night with his dead behind him and has the terrified mayor give him the shrine's silver candlesticks. Frightened hands still count. The lantern is finished, late.",
        sets: ["lantern_finished"],
      },
      {
        id: "c_door_breaks",
        when: { allOf: ["lantern_finished"], afterScene: 45 },
        preventedBy: { anyOf: ["deep_door_held", "corvane_stopped", "lantern_destroyed"] },
        event: "The dead break the Deep Door and pour up through the mine. The Hollow Teeth flee their warrens to the edge of the village, where frightened villagers take them for an attack. That night the dead walk into Blackstone, and the shrine is full of people until dawn.",
        sets: ["door_broken"],
      },
      {
        id: "c_king_wakes",
        when: { allOf: ["lantern_finished"], afterScene: 60 },
        preventedBy: { anyOf: ["corvane_stopped", "lantern_destroyed", "king_at_rest"] },
        event: "King Orrin wakes and the Ember Crown is lit. Every grave on the ridge empties, and the dead march down the valley road.",
        sets: ["king_woken"],
      },
    ],
  },

  factions: [
    {
      id: "f_village",
      name: "Blackstone village",
      goal: "Survive the winter without the mine.",
      leader: "npc_venn",
      resources: ["about sixty people, few of them fighters", "Hobb the watchman", "the shrine", "the valley road out"],
      allies: ["f_bell"],
      enemies: [],
      attitude: "neutral",
      wantsFromPlayer: "Bring the missing home and make the goblins stop.",
      ifIgnored: "Works itself up to a torch-and-pitchfork raid on the goblin camp: deaths on both sides, and the Deep Door unguarded while the goblins fight.",
    },
    {
      id: "f_hollow_teeth",
      name: "The Hollow Teeth",
      goal: "Keep the oath, feed the clan, and keep what is behind the Deep Door below it.",
      leader: "npc_grukka",
      resources: ["about twenty goblins, eight of them warriors", "the old tunnels, known in the dark", "the oath, taken more seriously than the village ever has"],
      allies: ["f_bell"],
      enemies: ["f_lamplighter"],
      attitude: "wary",
      wantsFromPlayer: "The toll paid or the oath honoured some other way, and help against what scratches at the Deep Door.",
      ifIgnored: "Take another villager as surety every few days while Snik talks of taking the grain. If the Deep Door breaks, they flee into the village, which will take it as an attack.",
    },
    {
      id: "f_bell",
      name: "The keepers of the Quiet Bell",
      goal: "Keep the dead asleep, as the keepers promised long ago.",
      leader: "npc_pell",
      resources: ["the Quiet Bell", "the shrine's old records", "one stubborn old woman"],
      allies: ["f_village", "f_hollow_teeth"],
      enemies: ["f_lamplighter"],
      attitude: "wary",
      wantsFromPlayer: "Someone young enough to carry the bell up to the barrow, and willing to believe her.",
      ifIgnored: "Pell climbs the ridge alone one night and does not come back. The bell is found later in the barrow-field grass.",
    },
    {
      id: "f_lamplighter",
      name: "The Lamplighter's dead",
      goal: "Wake King Orrin and light the Ember Crown.",
      leader: "npc_corvane",
      resources: ["the Grave Lantern", "the barrow-field's skeletons", "Tam Holt, entranced"],
      allies: [],
      enemies: ["f_hollow_teeth", "f_bell"],
      attitude: "hostile",
      wantsFromPlayer: "To be left alone, or for the player to stand aside.",
      ifIgnored: "The villain's clock runs out.",
    },
  ],

  npcs: [
    {
      id: "npc_venn",
      name: "Aldous Venn",
      role: "mayor of Blackstone",
      description: "A heavy, careful man in a good coat gone shiny at the elbows; his chain of office is always polished.",
      personality: "Proud and anxious, generous in public, mean with the truth.",
      motivation: "Blackstone's survival and his standing in it: he cannot be the mayor who let the village die.",
      fears: "Being found out; the village emptying; goblins coming for him personally.",
      values: "Order, appearances, the village's good name.",
      secrets: ["t_grain_toll", "t_mayor_selling_silver", "t_lantern_mark"],
      knowledge: ["the toll's terms, as he chose to read them", "exactly how much silver went up on Wenna's cart and what it paid", "the buyer writes like a scholar"],
      relationships: ["leans on Wenna, who owes him money", "dismisses Pell as superstitious", "Hobb answers to him"],
      attitude: "neutral",
      speech: "Over-formal civic phrases; answers questions about money with questions about safety.",
      currentGoal: "Keep the disappearances blamed on goblins until the buyer's last payment comes, then pay the village's debts and never dig again.",
      faction: "f_village",
      location: "loc_mayors_house",
      token: "token_villager",
    },
    {
      id: "npc_hobb",
      name: "Hobb Varley",
      role: "Blackstone's only watchman",
      description: "A broad young man in a borrowed breastplate that does not fit, with a spear never used on anything but rats.",
      personality: "Honest, easily embarrassed, braver than he thinks.",
      motivation: "Do right by the village.",
      fears: "The ridge at night; letting the mayor down.",
      values: "Duty, his neighbours.",
      secrets: ["t_dead_walk_ridge"],
      knowledge: ["the mayor told him to stop talking about ghosts", "he found goblin tracks at the mill and was told to leave them be", "Pell has been trying to tell people something for weeks"],
      relationships: ["answers to the mayor", "sweet on Bessa Crane, one of the missing", "fond of Pell, who taught him his letters"],
      attitude: "friendly",
      speech: "Sir or ma'am to everyone; rambles when nervous.",
      currentGoal: "Find the missing three without going up the ridge in the dark.",
      faction: "f_village",
      location: "loc_square",
      token: "token_guard",
    },
    {
      id: "npc_wenna",
      name: "Wenna Holt",
      role: "the village carter, Tam's mother",
      description: "A wiry woman with rope-burned hands and a cart she cannot stop fixing.",
      personality: "Hard-working, frightened, angry at herself.",
      motivation: "Get her son back.",
      fears: "That the crates she carried are why Tam is gone.",
      values: "Family; paying what she owes.",
      secrets: ["t_mayor_selling_silver", "t_lantern_mark"],
      knowledge: ["six sealed crates hauled from the mine to the cairn at night, for the mayor", "Tam asked what was in them the day before he vanished", "she hauled the goblins' grain until the mayor stopped it"],
      relationships: ["owes Venn a debt she cannot pay", "Tam's mother", "friendly with Hobb"],
      attitude: "neutral",
      speech: "Short and plain; swallows her words when the mayor is near.",
      currentGoal: "Find Tam without telling anyone about the crates, because the mayor said that would ruin her.",
      faction: "f_village",
      location: "loc_carters_yard",
      token: "token_villager",
    },
    {
      id: "npc_pell",
      name: "Ilse Pell",
      role: "sexton of the shrine of the Quiet Bell",
      description: "A small, sharp old woman with ink-stained fingers and a ring of iron keys at her belt.",
      personality: "Stubborn and dry, kind under it, tired of not being listened to.",
      motivation: "Keep the promise her family made to the dead.",
      fears: "That the rite is forgotten and she is too old to perform it.",
      values: "Rest for the dead, honesty, the old courtesies.",
      secrets: ["t_oath_seal", "t_silver_given", "t_bell_rite", "t_crown_price"],
      knowledge: ["King Orrin's name, and that he was buried crowned", "the bell's rite came to her from her grandmother"],
      relationships: ["respects Grukka, whose grandmother swore the oath to hers", "despairs of Venn", "taught Hobb his letters"],
      attitude: "wary",
      speech: "Clipped and dry; quotes old rhymes; answers questions with questions.",
      currentGoal: "Find someone who will believe her and carry the bell up to the barrow, since her knees will not.",
      faction: "f_bell",
      location: "loc_shrine",
      token: "token_robed_figure",
    },
    {
      id: "npc_grukka",
      name: "Grukka Two-Knives",
      role: "chief of the Hollow Teeth",
      description: "A grey-skinned goblin with a notched ear and two mismatched knives, older than most goblins live to be.",
      personality: "Blunt, patient, dryly funny, never bluffs.",
      motivation: "Her clan's survival and honour: the oath is what makes the Hollow Teeth more than vermin in the village's eyes.",
      fears: "What wakes behind the Deep Door; her young warriors dying for a village that cheats them.",
      values: "Oaths kept, debts paid, children fed.",
      secrets: ["t_goblins_took_two", "t_tam_below", "t_oath_seal"],
      knowledge: ["the mayor stopped the grain and sent men to dig at the mine's bottom", "something has scratched at the Deep Door from the far side for a month"],
      relationships: ["despises Venn as an oath-breaker", "respects Pell", "her nephew Snik is the clan's hothead"],
      attitude: "wary",
      speech: "Short sentences in trader's village-speech; calls the player walker.",
      currentGoal: "Get the toll paid, or something worth as much, before her clan starves or the Deep Door gives.",
      faction: "f_hollow_teeth",
      location: "loc_goblin_camp",
      token: "token_goblin",
    },
    {
      id: "npc_snik",
      name: "Snik",
      role: "Grukka's nephew, the youngest Hollow Teeth warrior",
      description: "A wiry young goblin with too many knives and a shield painted with a grinning mouth.",
      personality: "Loud, proud, reckless, desperate to be taken seriously.",
      motivation: "Prove himself a warrior to his aunt and the clan.",
      fears: "Being laughed at; the scratching at the Deep Door, which he will not admit.",
      values: "Courage as he understands it, which is mostly shouting.",
      secrets: [],
      knowledge: ["where the captives are kept", "the quickest way down the mine"],
      relationships: ["Grukka's nephew", "thinks the village owes the clan blood, not grain"],
      attitude: "hostile",
      speech: "Boasts, challenges, insults the player's shoes.",
      currentGoal: "Raid the village for the unpaid grain and come home a hero.",
      faction: "f_hollow_teeth",
      location: "loc_goblin_camp",
      token: "token_goblin",
    },
    {
      id: "npc_corvane",
      name: "Corvane Ash",
      role: "the Lamplighter, once a royal archivist",
      description: "A thin man in a scholar's black coat, grey before his time, carrying a grey-silver lantern that burns with a cold blue flame.",
      personality: "Courteous, precise, exhausted, utterly certain.",
      motivation: "Bring his daughter Lise back from death.",
      fears: "Being too late; forgetting her face.",
      values: "Knowledge, promises, his daughter.",
      secrets: ["t_corvane_is_buyer", "t_corvane_daughter", "t_silver_given"],
      knowledge: ["the rite that wakes King Orrin", "how the Grave Lantern works", "the history of every king on the ridge"],
      relationships: ["Lise's father", "buys from the mayor by letter and has never met him", "keeps Tam as lamp-bearer and feeds him carefully"],
      attitude: "wary",
      speech: "Soft, formal, archival; corrects people's history; never raises his voice.",
      currentGoal: "Finish the lantern and light the crown before anyone in the village understands what he is doing.",
      faction: "f_lamplighter",
      location: "loc_barrow_halls",
      token: "token_robed_figure",
    },
    {
      id: "npc_tam",
      name: "Tam Holt",
      role: "the missing carter's son, entranced",
      description: "A gangly fifteen-year-old with a blank, peaceful face, carrying an unlit lantern pole.",
      personality: "Cheeky and curious when himself; empty and humming now.",
      motivation: "None while entranced; once woken, to go home to his mother.",
      fears: "Once woken: the dark, and the cold man.",
      values: "His mother, his mates, a good joke.",
      secrets: [],
      knowledge: ["the way through the barrow halls", "where Corvane sleeps", "Corvane talks to a small painted portrait every night"],
      relationships: ["Wenna's son", "Corvane's lamp-bearer, for now"],
      attitude: "neutral",
      speech: "Entranced, hums and says nothing. Woken, talks too fast and cries.",
      currentGoal: "Carry the lantern pole wherever the Lamplighter walks.",
      faction: "f_lamplighter",
      location: "loc_barrow_halls",
      token: "token_villager",
    },
    {
      id: "npc_orrin",
      name: "King Orrin the Unburied",
      role: "the dead king beneath the ridge",
      description: "A tall skeleton in rotted royal silks on a stone bier, a crown of dark gold on his skull.",
      personality: "Asleep. If woken: cold, regal, sure the valley is still his.",
      motivation: "To sleep. If woken, to rule again.",
      fears: "The Quiet Bell.",
      values: "Obedience.",
      secrets: ["t_crown_price"],
      knowledge: ["what the crown does to its wearer, because it did it to him"],
      relationships: ["sworn to sleep by the keepers of the Quiet Bell"],
      attitude: "hostile",
      speech: "Asleep, nothing. Woken, few words, all commands.",
      currentGoal: "Sleep.",
      faction: "f_lamplighter",
      location: "loc_kings_tomb",
      token: "token_skeleton",
    },
  ],

  locations: [
    {
      id: "loc_square",
      name: "Blackstone square",
      cells: [{ cx: 0, cy: 0 }],
      description: "A cobbled square around a deep stone well and the notice board, the mayor's hall east, the shrine west, the mine road north, the lane south to the carter's yard.",
      atmosphere: "By day, a tired village pretending things are normal. At dusk, torches and angry voices.",
      features: ["the well", "the notice board with three names on it", "the crowd"],
      secrets: ["t_dead_walk_ridge"],
      connected: ["loc_mayors_house", "loc_shrine", "loc_carters_yard", "loc_mine_road"],
      threats: ["a crowd that wants someone to blame"],
      discoverable: ["Hobb's account of the ridge", "who in the crowd is frightened and who is angry"],
    },
    {
      id: "loc_mayors_house",
      name: "The mayor's house",
      cells: [{ cx: 1, cy: 0 }],
      description: "The best house in Blackstone: the village hall below, and above it the mayor's cold, tidy study.",
      atmosphere: "Polished, cold and quiet. The study hearth is full of burnt paper.",
      features: ["the hall", "the tithe ledger on the study shelf", "a locked desk", "burnt paper in the cold hearth"],
      secrets: ["t_grain_toll", "t_mayor_selling_silver", "t_lantern_mark"],
      connected: ["loc_square"],
      threats: ["being caught by the mayor, who will have Hobb throw the player out of the village"],
      discoverable: ["the tithe ledger", "the buyer's letters", "a lantern mark on a burnt corner of paper"],
    },
    {
      id: "loc_shrine",
      name: "The shrine of the Quiet Bell",
      cells: [{ cx: -1, cy: 0 }],
      description: "A cold stone chapel older than Blackstone and too big for it, a small dark bronze hand bell on a hook over the altar, a path north up the ridge.",
      atmosphere: "Still and clean, beeswax and old stone, always colder than outside.",
      features: ["the altar", "the Quiet Bell and its inscription", "old carvings of a sleeping king", "the shrine records", "the path to the barrow-field"],
      secrets: ["t_oath_seal", "t_bell_rite", "t_crown_price", "t_silver_given"],
      connected: ["loc_square", "loc_barrow_field"],
      threats: [],
      discoverable: ["the bell's inscription", "the oath's old terms, in the records"],
    },
    {
      id: "loc_carters_yard",
      name: "Wenna's yard",
      cells: [{ cx: 0, cy: 1 }],
      description: "A muddy yard: a stable, a cart, a lean-to house, and Tam's coat still on its peg.",
      atmosphere: "Busy hands and an empty doorway.",
      features: ["the cart, grey silver dust in its bed and a lantern scratched into one board", "the stable", "Tam's coat"],
      secrets: ["t_mayor_selling_silver", "t_lantern_mark"],
      connected: ["loc_square"],
      threats: [],
      discoverable: ["the silver dust", "Wenna's account of the crates"],
    },
    {
      id: "loc_mine_road",
      name: "The old mine road",
      cells: [{ cx: 0, cy: -1 }],
      description: "A rutted cart road climbing north through dark pine woods to the old mine, tracks in the mud.",
      atmosphere: "Pine-quiet. Things watch from the trees.",
      features: ["the cart ruts", "drag marks in the mud", "a goblin lookout post in a tree"],
      secrets: ["t_goblins_took_two", "t_tam_below"],
      connected: ["loc_square", "loc_goblin_camp", "loc_barrow_field"],
      threats: ["a goblin scout"],
      discoverable: ["two sets of tracks: goblin, and a boy's boots walking alone"],
    },
    {
      id: "loc_goblin_camp",
      name: "The Hollow Teeth camp",
      cells: [{ cx: 0, cy: -2 }],
      description: "Hide tents and old mine timbers at the mine mouth around a carved oath stone, two captives under an awning.",
      atmosphere: "Watchful and hungry. Half the warriors sleep facing the mine, not the road.",
      features: ["the oath stone", "the captives' awning and ropes", "the mine mouth", "the cook fire"],
      secrets: ["t_goblins_took_two", "t_oath_seal", "t_tam_below", "t_grain_toll"],
      connected: ["loc_mine_road", "loc_upper_mine", "loc_barrow_field"],
      threats: ["Snik and two warriors", "a lie Grukka catches"],
      discoverable: ["what the oath stone means", "why the goblins fear the mine"],
    },
    {
      id: "loc_upper_mine",
      name: "The upper workings",
      cells: [{ cx: 1, cy: -2 }],
      description: "The old mine's timbered upper tunnels where the Hollow Teeth live, and the head of the shaft down, breathing cold.",
      atmosphere: "Smoky and close. At night, a faint scratching from below.",
      features: ["goblin sleeping niches", "the shaft head and its ladders", "old ore carts"],
      secrets: ["t_oath_seal"],
      connected: ["loc_goblin_camp", "loc_lower_mine"],
      threats: ["goblins who did not agree to the player being here"],
      discoverable: ["the scratching from below, after dark"],
    },
    {
      id: "loc_lower_mine",
      name: "The lower workings and the Deep Door",
      cells: [{ cx: 1, cy: -3 }],
      description: "The half-flooded bottom of the mine. Fresh pick marks show where the mayor's men broke into older, smoother tunnels. On the west side, the Deep Door: a round stone seal carved with a bell.",
      atmosphere: "Cold water, dripping, and something on the far side of the stone.",
      features: ["the Deep Door and its carvings", "a hand-wide gap at its edge", "the miners' breach", "abandoned picks and a weight ledger", "timbers that could brace the door"],
      secrets: ["t_oath_seal", "t_mayor_selling_silver", "t_tam_below", "t_crown_price"],
      connected: ["loc_upper_mine", "loc_barrow_halls"],
      threats: ["the dead working at the door from the far side"],
      discoverable: ["the carvings", "a boy's boot prints going through the gap"],
    },
    {
      id: "loc_barrow_field",
      name: "The barrow-field",
      cells: [
        { cx: -1, cy: -1, hint: "the lower barrow-field: grassed grave mounds climbing the ridge, standing stones, the path up from the shrine" },
        { cx: -1, cy: -2, hint: "the upper barrow-field: the oldest mounds, wind, and footprints that are not a person's" },
      ],
      description: "Long grassed grave mounds climbing the ridge above the village, standing stones between them.",
      atmosphere: "Wind and silence by day. At night, a cold blue light moving among the mounds.",
      features: ["grave mounds", "standing stones", "the view down over Blackstone", "bony footprints in the frost"],
      secrets: ["t_dead_walk_ridge"],
      connected: ["loc_shrine", "loc_mine_road", "loc_goblin_camp", "loc_cairn"],
      threats: ["skeletons walking at night"],
      discoverable: ["the dead walking", "a blue light that moves when they move"],
    },
    {
      id: "loc_cairn",
      name: "The cairn",
      cells: [{ cx: -1, cy: -3 }],
      description: "A tall stack of black stones at the top of the ridge where the buyer leaves payment, and behind it a barrow mouth recently dug open.",
      atmosphere: "Exposed, windy, and watched.",
      features: ["the payment niche", "the dug-open barrow mouth, lantern soot on its lintel", "a steep drop on the east side"],
      secrets: ["t_lantern_mark", "t_corvane_is_buyer", "t_tam_below"],
      connected: ["loc_barrow_field", "loc_barrow_halls"],
      threats: ["the Lamplighter's two-skeleton guard, at midnight"],
      discoverable: ["the archive seal on a payment purse", "a boy's boot print in the dust"],
    },
    {
      id: "loc_barrow_halls",
      name: "The barrow halls",
      cells: [{ cx: 0, cy: -3 }],
      description: "Low stone halls under the ridge lined with niches of bones, every third niche empty. Corvane camps here on a coffin lid.",
      atmosphere: "Cold, dry, and humming: Tam hums as he walks.",
      features: ["the niches", "Corvane's camp, his journal and a small painted portrait of a girl", "the back of the Deep Door to the east", "the way down to the tomb in the north"],
      secrets: ["t_corvane_daughter", "t_tam_below", "t_silver_given"],
      connected: ["loc_cairn", "loc_lower_mine", "loc_kings_tomb"],
      threats: ["the Lamplighter's dead"],
      discoverable: ["Corvane's journal", "Tam"],
    },
    {
      id: "loc_kings_tomb",
      name: "King Orrin's tomb",
      cells: [{ cx: 0, cy: -4 }],
      description: "A round chamber at the bottom of the barrow: King Orrin crowned on a stone bier under the Grave Lantern's cold light.",
      atmosphere: "Cold enough to see breath; the silence of something about to wake.",
      features: ["the bier and its inscription", "the Ember Crown", "the Grave Lantern, if Corvane is here", "steps down from the halls"],
      secrets: ["t_crown_price"],
      connected: ["loc_barrow_halls"],
      threats: ["Corvane's last guard", "the king, if he wakes"],
      discoverable: ["the inscription", "what the crown does"],
    },
  ],

  acts: [
    {
      id: "act_something_wrong",
      title: "Act I: Something Is Wrong in Blackstone",
      goal: "Find out what happened to the three missing villagers.",
      conflict: "The village blames the goblins, the mayor wants it that way, and the goblins really did take two of them, for a reason nobody will say aloud.",
      revelation: "The goblins are not the threat. The mayor broke the village's oath, and what the goblins have guarded for generations is waking.",
      advanceWhen: { allOf: ["b_mayor_involved", "b_something_below"] },
      transition:
        "The player knows the mayor broke the oath and that something under the ridge stirs. The story is now whoever buys the silver and whatever is behind the Deep Door. Let this act's people come to the player: Wenna is ready to talk, Pell to be believed, and Grukka wants a word.",
      beats: [
        {
          id: "b_mayor_involved",
          text: "The player discovers the mayor is involved.",
          required: "Evidence tying the mayor to the unpaid toll or the silver.",
          canHappenThrough: ["the tithe ledger", "the buyer's letters", "Grukka's testimony", "Wenna's crates", "the mayor confessing under pressure", "the picks in the lower mine"],
          notBefore: { anyOf: ["evidence_against_mayor", "t_grain_toll", "cl_wennas_crates"] },
          result: "The mayor grows suspicious of the player and starts burning what he can.",
        },
        {
          id: "b_something_below",
          text: "The player learns something under the ridge is waking.",
          required: "Any real sign of the dead or the Deep Door.",
          canHappenThrough: ["Hobb's account", "the scratching below the mine", "the oath stone", "Grukka", "Pell", "seeing the ridge walkers"],
          notBefore: { anyOf: ["cl_hobbs_account", "cl_scratching", "cl_oath_stone", "t_dead_walk_ridge", "t_oath_seal", "c_ridge_walkers"] },
          result: "A village problem becomes something under the ridge.",
        },
        {
          id: "b_pell_heard",
          text: "Someone finally listens to Sexton Pell.",
          required: "The player visits the shrine and takes Pell seriously.",
          canHappenThrough: ["asking about the goblins", "asking about the ridge", "bringing her evidence", "Hobb sending them", "helping her with something small first"],
          result: "Pell begins to trust the player: the oath's old terms now, the bell's rite whenever they need it.",
          sets: ["pell_trusts_player"],
        },
      ],
      arcs: [
        {
          id: "a_missing_three",
          name: "The Missing Three",
          purpose: "Pull the player into the village's problem and let them find the first loose thread.",
          startingState: "Three missing, notices on the board, a mayor blaming goblins and offering a reward, a watchman told to ignore the tracks he found.",
          objective: "Find out where the missing went.",
          conflict: "The mayor steers everyone toward the goblins and away from his ledgers; Wenna is too frightened to talk; Hobb is loyal to the mayor; nobody listens to Pell.",
          npcs: ["npc_venn", "npc_hobb", "npc_wenna", "npc_pell"],
          locations: ["loc_square", "loc_mayors_house", "loc_carters_yard", "loc_shrine", "loc_mine_road"],
          clues: [
            {
              id: "cl_tracks",
              text: "Bare goblin footprints and drag marks from the mill up the mine road, two weeks old, and a fresher set: a boy's boots walking alone, uphill, toward the mine.",
              source: "the old mine road",
              pointsTo: ["t_goblins_took_two", "t_tam_below"],
            },
            {
              id: "cl_tithe_ledger",
              text: "The tithe ledger: a grain payment to 'the Teeth' every season for ninety years in a dozen hands, stopping three months ago in the mayor's.",
              source: "the study shelf, in plain sight",
              pointsTo: ["t_grain_toll"],
              sets: ["evidence_against_mayor"],
            },
            {
              id: "cl_buyer_letters",
              text: "Letters in a fine scholar's hand ordering 'grave-silver, as before', promising payment at the cairn, each signed with a small drawn lantern.",
              source: "the mayor's locked desk",
              pointsTo: ["t_mayor_selling_silver", "t_lantern_mark"],
              sets: ["evidence_against_mayor"],
            },
            {
              id: "cl_hobbs_account",
              text: "Hobb has twice seen two skeletons walking the ridge at dusk, and the mayor told him to stop talking about ghosts.",
              source: "Hobb, once he trusts the player or is caught alone",
              pointsTo: ["t_dead_walk_ridge"],
            },
            {
              id: "cl_wennas_crates",
              text: "Wenna has hauled six sealed, heavy crates from the mine to the cairn at night for the mayor, and Tam asked what was in them the day before he vanished.",
              source: "Wenna, if the player promises to look for Tam or presses her kindly",
              pointsTo: ["t_mayor_selling_silver", "t_tam_below"],
            },
            {
              id: "cl_bell_inscription",
              text: "Tiny letters around the Quiet Bell's rim: 'Rung below, he sleeps.'",
              source: "the bell in the shrine",
              pointsTo: ["t_bell_rite"],
            },
          ],
          approaches: ["question villagers, Hobb and Wenna", "search the study, openly or by night", "follow the tracks", "ask Pell, whom everyone ignores", "go straight to the goblins", "take the mayor's commission and see where it leads"],
          outcomes: [
            {
              id: "o_mayor_exposed",
              text: "The player exposes the mayor before the village, with evidence.",
              sets: ["mayor_exposed"],
              attitudes: [
                { id: "npc_venn", attitude: "hostile" },
                { id: "f_village", attitude: "friendly" },
              ],
            },
            {
              id: "o_mayor_confessed",
              text: "Confronted in private, the mayor confesses and begs the player to keep it quiet.",
              sets: ["mayor_confessed"],
              attitudes: [{ id: "npc_venn", attitude: "unfriendly" }],
            },
            {
              id: "o_mayor_covered",
              text: "The player agrees to help the mayor keep it quiet.",
              sets: ["mayor_ally"],
              attitudes: [
                { id: "npc_venn", attitude: "allied" },
                { id: "npc_pell", attitude: "unfriendly" },
              ],
            },
            {
              id: "o_village_left",
              text: "The player walks away from the village's problem.",
              sets: ["village_abandoned"],
              attitudes: [{ id: "f_village", attitude: "unfriendly" }],
            },
          ],
          rewards: ["Hobb's trust and his spear beside the player", "Wenna's trust", "a village that listens to the player over the mayor"],
          failure: "If nobody pulls the thread, the village raids the goblin camp itself, and the arc resolves badly.",
          worldChanges: ["the mayor's standing", "whether Blackstone listens to the player or the mayor"],
          scenes: [
            {
              id: "s_notice_board",
              name: "The notice board",
              location: "loc_square",
              situation: "The mayor reads Tam Holt's name off a fresh notice to an angry crowd and promises a reward for goblin ears.",
              npcsPresent: ["npc_venn", "npc_hobb", "npc_wenna"],
              whatTheyWant: "Venn, a hero to fight goblins. Hobb, to be told what to do. Wenna, for everyone to stop talking and start looking.",
              playerKnows: "Three are missing and the village blames goblins.",
              hidden: "Venn's hands shake whenever the mine comes up. Wenna will not look at him.",
              interactions: ["read the notices", "work the crowd", "question the mayor", "talk to Hobb", "watch Wenna"],
              checks: [
                { skill: "Insight", dc: 12, reveals: "the mayor fears something other than goblins" },
                { skill: "Insight", dc: 12, reveals: "Wenna hides something, and hates the mayor for it" },
              ],
              escalation: "If the player sides loudly with the goblins, the crowd turns ugly and Venn has Hobb walk them out of the square.",
              outcomes: ["the player takes the mayor's commission", "the player starts asking their own questions"],
            },
            {
              id: "s_mayors_study",
              name: "The mayor's study",
              location: "loc_mayors_house",
              situation: "A cold, tidy room above the hall: ledgers on the shelf, a locked desk, a hearth full of burnt paper.",
              npcsPresent: ["npc_venn"],
              whatTheyWant: "Venn wants the player out, politely if possible.",
              playerKnows: "The mayor keeps the village's records here.",
              hidden: "The tithe ledger on the shelf; the buyer's letters in the desk; in the hearth, a burnt corner of an older letter with the lantern mark still on it.",
              interactions: ["search the shelves", "pick or force the desk", "sift the hearth", "talk the mayor round", "come back at night"],
              checks: [
                { skill: "Investigation", dc: 10, reveals: "the tithe ledger and when payments stop" },
                { skill: "Sleight of Hand", dc: 13, reveals: "the desk lock opens" },
                { skill: "Investigation", dc: 15, reveals: "the desk key, under the drawer" },
                { skill: "Investigation", dc: 12, reveals: "the lantern mark on the burnt corner" },
              ],
              escalation: "Caught, the player is run out of the village by Hobb on Venn's word, and Venn burns the letters that night unless stopped.",
              outcomes: ["the player finds the evidence", "the player is caught and thrown out", "the player talks Venn into showing them"],
            },
            {
              id: "s_carters_yard",
              name: "Wenna's yard",
              location: "loc_carters_yard",
              situation: "Wenna loads an empty cart with nothing, to keep her hands busy. Tam's coat is still on its peg.",
              npcsPresent: ["npc_wenna"],
              whatTheyWant: "Tam back, and the fear that the crates are why he is gone kept quiet.",
              playerKnows: "Her son is one of the missing.",
              hidden: "The crates, the cairn, and Tam's questions.",
              interactions: ["offer to find Tam", "ask about her work", "look over the cart", "ask about the mayor"],
              checks: [
                { skill: "Insight", dc: 12, reveals: "she hides something about her work" },
                { skill: "Investigation", dc: 11, reveals: "the silver dust and the lantern scratched in the cart" },
              ],
              escalation: "Pressed hard or threatened, she shuts the gate and goes to warn the mayor.",
              outcomes: ["Wenna tells the player about the crates", "Wenna sends the player away"],
            },
            {
              id: "s_shrine",
              name: "The Quiet Bell",
              location: "loc_shrine",
              situation: "Sexton Pell sweeps a floor that is already clean, under a small bronze bell nobody looks at.",
              npcsPresent: ["npc_pell"],
              whatTheyWant: "Pell wants someone to believe her: the goblins are not the enemy, and the bell is not there to be looked at.",
              playerKnows: "There is a shrine and an old woman nobody listens to.",
              hidden: "Pell gives the oath to anyone who listens, and the rite only to someone she trusts.",
              interactions: ["ask about the bell", "ask about the goblins", "ask about the ridge", "help her with something small first", "read the bell's inscription"],
              checks: [
                { skill: "Religion", dc: 13, reveals: "the bell's inscription" },
                { skill: "Insight", dc: 10, reveals: "she is frightened, not mad" },
              ],
              escalation: "Mocked or hurried, Pell shuts the shrine door and opens it again only to someone Hobb or Wenna vouches for.",
              outcomes: ["Pell is heard", "Pell is dismissed"],
            },
          ],
          encounters: [
            {
              id: "e_crowd",
              name: "The angry square",
              type: "social",
              difficulty: "easy",
              location: "loc_square",
              participants: ["Mayor Venn", "Hobb", "a dozen frightened villagers"],
              environment: "The square at dusk: torches, the well, the notice board.",
              objective: "Keep the village from marching on the goblins.",
              special: ["the crowd follows whoever sounds most certain"],
              npcBehavior: "Venn pushes for a raid, Hobb hesitates, Wenna says nothing.",
              triggers: ["the player speaks up in the square", "the ridge walkers are seen"],
              success: "The village waits for the player to look into it.",
              failure: "A dozen villagers set out for the mine at dawn.",
              alternatives: ["calm them (Persuasion DC 13)", "shout them down (Intimidation DC 13)", "show evidence against the mayor"],
              rewards: ["the village's patience", "Hobb's respect"],
            },
          ],
        },
        {
          id: "a_hollow_teeth",
          name: "The Hollow Teeth",
          purpose: "Turn 'the goblins did it' into 'the goblins did it, and here is why', and introduce what is under the mine.",
          startingState: "The Hollow Teeth hold Bessa and Jory at the mine mouth. Snik wants to raid the village for the unpaid grain; Grukka is holding him back, barely.",
          objective: "Get the captives back.",
          conflict: "The goblins want the toll, the village will not pay, Snik wants blood, and the warriors are on edge because something scratches at the Deep Door from the far side.",
          npcs: ["npc_grukka", "npc_snik"],
          locations: ["loc_mine_road", "loc_goblin_camp", "loc_upper_mine"],
          clues: [
            {
              id: "cl_goblin_testimony",
              text: "Grukka's account: ninety years of grain for guarding the bottom of the mine; the mayor stopped paying and sent men to dig silver there instead; a village boy went down the shaft alone and did not come back.",
              source: "Grukka, if the player talks before fighting",
              pointsTo: ["t_grain_toll", "t_mayor_selling_silver", "t_tam_below"],
              sets: ["evidence_against_mayor"],
            },
            {
              id: "cl_scratching",
              text: "Scratching at night from beyond the stone the goblins guard, and a cold coming up the shaft.",
              source: "the upper workings, after dark",
              pointsTo: ["t_oath_seal", "t_dead_walk_ridge"],
            },
            {
              id: "cl_oath_stone",
              text: "The camp's carved stone: a bell, a goblin hand clasping a human one, and a crowned figure lying down beneath.",
              source: "the oath stone in the goblin camp",
              pointsTo: ["t_oath_seal"],
            },
          ],
          approaches: ["parley with Grukka", "pay the toll from their own pocket or the village's", "sneak in and free the captives", "fight their way in", "face Snik alone and shame him", "bring Pell, whom Grukka respects"],
          outcomes: [
            {
              id: "o_captives_negotiated",
              text: "The player negotiates Bessa and Jory's release on a promise the toll will be paid.",
              sets: ["captives_freed", "goblin_deal"],
              attitudes: [
                { id: "f_hollow_teeth", attitude: "friendly" },
                { id: "npc_grukka", attitude: "friendly" },
              ],
            },
            {
              id: "o_captives_stolen",
              text: "The player frees the captives without the goblins' consent.",
              sets: ["captives_freed"],
              attitudes: [{ id: "f_hollow_teeth", attitude: "unfriendly" }],
            },
            {
              id: "o_goblins_fought",
              text: "The player fights the Hollow Teeth and takes the captives by force.",
              sets: ["captives_freed", "goblins_bloodied"],
              attitudes: [
                { id: "f_hollow_teeth", attitude: "hostile" },
                { id: "npc_grukka", attitude: "hostile" },
              ],
            },
            {
              id: "o_goblins_allied",
              text: "The player swears to see the oath honoured, and the Hollow Teeth agree to stand with them against what is below.",
              sets: ["captives_freed", "goblin_deal", "goblin_alliance"],
              attitudes: [
                { id: "f_hollow_teeth", attitude: "allied" },
                { id: "npc_grukka", attitude: "allied" },
              ],
            },
          ],
          rewards: ["the captives home and the village grateful", "Grukka's knowledge of the mine", "goblin guides down the shaft, if allied"],
          failure: "Left alone, Snik raids the village within days, someone dies on each side, and the village marches on the camp in return.",
          worldChanges: ["whether the goblins keep guarding the Deep Door, help the player, or flee", "whether the village owes the goblins or hates them"],
          scenes: [
            {
              id: "s_mine_mouth",
              name: "The mine mouth",
              location: "loc_goblin_camp",
              situation: "Two goblin sentries see the player long before the player sees them. Bessa and Jory sit roped under an awning, fed and bored.",
              npcsPresent: ["npc_grukka", "npc_snik"],
              whatTheyWant: "Grukka, the toll, and to know whether the player speaks for the village. Snik, an excuse.",
              playerKnows: "Goblins live here; the missing might be here.",
              hidden: "The goblins are frightened, and not of the player.",
              interactions: ["call out and parley", "creep in", "watch the camp", "challenge Snik", "show the oath stone respect"],
              checks: [
                { skill: "Stealth", dc: 13, reveals: "getting close unseen" },
                { skill: "Persuasion", dc: 13, reveals: "Grukka talks instead of fighting" },
                { skill: "Insight", dc: 11, reveals: "they keep glancing at the mine, not the player" },
              ],
              combat: "e_camp_fight",
              escalation: "A drawn weapon or a creeper caught, and Snik attacks with one warrior while Grukka lets him, to see what the player is made of.",
              outcomes: ["a deal", "a rescue", "a fight"],
            },
            {
              id: "s_listening_shaft",
              name: "The listening shaft",
              location: "loc_upper_mine",
              situation: "The shaft head at night. Goblins sit around it in silence, listening.",
              npcsPresent: [],
              whatTheyWant: "The scratching to stop, without being the ones who go down.",
              playerKnows: "Goblins guard this mine.",
              hidden: "The scratching is the dead, working at the Deep Door from the barrow side.",
              interactions: ["listen", "ask the goblins", "climb down"],
              checks: [{ skill: "Perception", dc: 12, reveals: "fingers on stone, more than one set" }],
              escalation: "If the player climbs down alone, the goblins neither stop nor follow them.",
              outcomes: ["the player hears it and comes away", "the player goes down to the Deep Door"],
            },
          ],
          encounters: [
            {
              id: "e_scout",
              name: "The lookout in the pines",
              type: "exploration",
              difficulty: "easy",
              location: "loc_mine_road",
              participants: ["one goblin scout on a platform ten feet up a tree"],
              environment: "Pine woods either side of a rutted road.",
              objective: "Get up the road without the camp being warned, or catch the scout.",
              special: ["the scout runs rather than fights", "if it gets away, the camp is ready and Snik waiting"],
              enemyBehavior: "Watches, then flees uphill to warn the camp; fights only if cornered.",
              triggers: ["the player walks up the mine road"],
              success: "The player reaches the camp unexpected, or with a scout who will talk.",
              failure: "The camp knows the player is coming.",
              alternatives: ["spot it first (Perception DC 12)", "sneak past (Stealth DC 12)", "call up and talk"],
              rewards: ["surprise", "a frightened goblin willing to say why the clan took the captives"],
            },
            {
              id: "e_parley",
              name: "Parley at the mine mouth",
              type: "social",
              difficulty: "medium",
              location: "loc_goblin_camp",
              participants: ["Grukka Two-Knives", "Snik", "a ring of goblins"],
              environment: "The cook fire, the oath stone, the dark mine mouth behind.",
              objective: "Free the captives without a fight.",
              special: ["Grukka never bluffs and respects those who do not", "a lie she catches (Insight against the player's Deception) ends the parley"],
              npcBehavior: "Grukka states terms plainly: the toll, or something worth it. Snik heckles.",
              triggers: ["the player approaches openly"],
              success: "Bessa and Jory walk home, and Grukka tells the player what the mayor did.",
              failure: "Grukka sends the player off with the captives still held, and Snik follows to see where they go.",
              alternatives: ["pay the toll", "promise to make the village pay", "offer to deal with the scratching below", "bring Pell"],
              rewards: ["the captives", "Grukka's testimony", "goblin guides"],
            },
            {
              id: "e_camp_fight",
              name: "Snik's ambush",
              type: "combat",
              difficulty: "medium",
              location: "loc_goblin_camp",
              participants: ["Snik (a goblin)", "one goblin warrior, two from level 2"],
              environment: "Tents, guy-ropes, a fire pit; the mine mouth gives cover.",
              objective: "Survive, and get the captives out.",
              special: ["Grukka fights only if the player kills a goblin", "if Snik goes down, the others stop and look to Grukka"],
              enemyBehavior: "Snik wants a duel to prove himself; the warrior hangs back and runs if hurt.",
              triggers: ["the player attacks", "Snik is provoked", "the player is caught freeing the captives"],
              success: "The goblins yield and the captives go free.",
              failure: "If the player goes down and lives, they wake roped beside Bessa and Jory, Grukka waiting to talk.",
              alternatives: ["yield and talk", "grab the captives and run"],
              rewards: ["the captives", "the goblins' fear instead of their respect"],
            },
          ],
        },
      ],
    },
    {
      id: "act_silver_road",
      title: "Act II: The Silver Road",
      goal: "Find out who buys the grave-silver, and what is behind the Deep Door.",
      conflict: "The buyer hides behind the dead, the mayor is desperate, the Deep Door is giving, and Tam is somewhere under the ridge.",
      revelation: "The buyer is Corvane Ash, the Lamplighter, and he is waking the king under the ridge.",
      advanceWhen: { allOf: ["b_lamplighter_named", "b_barrow_entered"] },
      transition:
        "The player knows the Lamplighter's name and has a way into the barrow. Whatever they decided about the mayor and the goblins, the rest plays out under the ridge. Corvane knows someone is coming; the dead are thicker and less patient now.",
      beats: [
        {
          id: "b_lamplighter_named",
          text: "The player learns who the buyer is.",
          required: "Something that names Corvane Ash or marks him unmistakably.",
          canHappenThrough: ["the archive seal", "meeting him at the cairn", "following the blue light", "Pell recognising the description", "Tam, if found early"],
          notBefore: { anyOf: ["cl_archive_seal", "cl_blue_light", "o_buyer_met", "t_corvane_is_buyer"] },
          result: "Corvane learns someone knows his name, and the dead start watching the village at night.",
        },
        {
          id: "b_barrow_entered",
          text: "The player finds the way into the barrow halls.",
          required: "A way in: the barrow mouth behind the cairn, or the gap at the Deep Door.",
          canHappenThrough: ["searching the cairn by day", "following the dead back from the cairn", "squeezing through the Deep Door's gap", "opening the Deep Door"],
          notBefore: { anyOf: ["barrow_way_found"] },
          result: "The way to the Lamplighter is open.",
        },
        {
          id: "b_tam_alive",
          text: "The player learns that Tam is alive.",
          required: "Real evidence he is alive under the ridge.",
          canHappenThrough: ["Grukka's sentries", "the boot prints by the Deep Door", "a glimpse of a boy with a lantern pole at the cairn", "the boot print behind the cairn"],
          result: "Wenna's hope becomes the player's reason.",
        },
      ],
      arcs: [
        {
          id: "a_the_buyer",
          name: "The Buyer at the Cairn",
          purpose: "Put a name and a face to the lantern mark.",
          startingState: "The mayor's last crate of silver is due at the cairn. The buyer collects at midnight while the dead walk the ridge.",
          objective: "Find out who the buyer is.",
          conflict: "He comes only at night, under the eyes of his dead, and the mayor will warn him if he can.",
          npcs: ["npc_wenna", "npc_venn", "npc_corvane", "npc_hobb"],
          locations: ["loc_carters_yard", "loc_barrow_field", "loc_cairn"],
          clues: [
            {
              id: "cl_archive_seal",
              text: "A wax seal on the payment purse: the royal archive's crossed keys, scratched through.",
              source: "the cairn's payment niche, or the purse in the mayor's desk",
              pointsTo: ["t_corvane_is_buyer"],
            },
            {
              id: "cl_blue_light",
              text: "A cold blue light moving among the barrows at night, skeletons walking beside it like an honour guard.",
              source: "the barrow-field after dark",
              pointsTo: ["t_corvane_is_buyer", "t_dead_walk_ridge"],
            },
            {
              id: "cl_cairn_tunnel",
              text: "Behind the cairn, a freshly dug barrow mouth, lantern soot on its lintel and a boy's boot print in the dust.",
              source: "the cairn, by day",
              pointsTo: ["t_tam_below"],
              sets: ["barrow_way_found"],
            },
          ],
          approaches: ["ride along on Wenna's last delivery", "stake out the cairn at night", "follow the dead back to their barrow", "have the mayor write to the buyer and set a trap", "search the cairn by day"],
          outcomes: [
            {
              id: "o_buyer_met",
              text: "The player meets the Lamplighter at the cairn and learns his name.",
              sets: ["met_corvane"],
            },
            {
              id: "o_silver_cut_off",
              text: "The player stops the last silver reaching him: the crate seized, the mayor stopped, or Wenna persuaded to refuse.",
              sets: ["silver_cut_off"],
              attitudes: [{ id: "npc_corvane", attitude: "unfriendly" }],
            },
            {
              id: "o_buyer_followed",
              text: "The player follows the dead back to their barrow.",
              sets: ["barrow_way_found"],
            },
          ],
          rewards: ["the villain's name", "the way into the barrow from the ridge", "Wenna's gratitude"],
          failure: "If the last silver reaches him, the lantern is finished on schedule.",
          worldChanges: ["whether Corvane knows the player is coming", "whether the lantern is finished on time"],
          scenes: [
            {
              id: "s_night_cairn",
              name: "The cairn at midnight",
              location: "loc_cairn",
              situation: "Wenna's crate sits at the cairn's foot. At midnight a cold blue light rises from the barrow behind it, and with it a thin man and two skeletons.",
              npcsPresent: ["npc_corvane"],
              whatTheyWant: "Corvane wants the silver and no witnesses; he would rather talk than fight, and rather leave than talk.",
              playerKnows: "Someone collects the silver here at night.",
              hidden: "The skeletons obey the lantern, not Corvane: out of its sight, they stop. Corvane is no fighter.",
              interactions: ["hide and watch", "step out and speak", "seize the crate", "go for the light", "follow him back"],
              checks: [
                { skill: "Stealth", dc: 13, reveals: "watching unseen" },
                { skill: "Arcana", dc: 13, reveals: "the dead move when the lantern moves" },
                { skill: "Persuasion", dc: 14, reveals: "Corvane stays and talks" },
              ],
              combat: "e_cairn_guard",
              escalation: "Threatened, Corvane steps back into the barrow and the two skeletons step forward.",
              outcomes: ["the player learns his name", "the player cuts off the silver", "the player follows him"],
            },
            {
              id: "s_ridge_at_dusk",
              name: "The ridge at dusk",
              location: "loc_barrow_field",
              situation: "The barrow-field as the light goes: frost on the mounds, and footprints in it that are only bone.",
              npcsPresent: [],
              whatTheyWant: "The dead want to walk their circuit and go back down.",
              playerKnows: "People say something walks up here.",
              hidden: "The walkers come from the cairn and return to it.",
              interactions: ["hide among the mounds", "follow the footprints", "wait for the light"],
              checks: [{ skill: "Survival", dc: 11, reveals: "the bone prints all lead to and from the cairn" }],
              escalation: "Seen, the player is chased by two skeletons, who stop at the first standing stone.",
              outcomes: ["the player sees the blue light", "the player finds where the dead go"],
            },
          ],
          encounters: [
            {
              id: "e_cairn_guard",
              name: "The lantern's guard",
              type: "combat",
              difficulty: "medium",
              location: "loc_cairn",
              participants: ["two skeletons, one at level 1"],
              environment: "A windy hilltop, grave mounds for cover, a steep drop east.",
              objective: "Survive, or get past to the light.",
              special: ["the skeletons stand still a round whenever the lantern is out of their sight", "Corvane does not fight; he leaves"],
              enemyBehavior: "They keep between the player and the lantern and never chase past the cairn.",
              triggers: ["the player threatens Corvane or the lantern", "the player is spotted"],
              success: "The dead fall, and the crate is the player's.",
              failure: "If the player goes down and lives, they wake at dawn on the hilltop, the crate gone, a small lantern drawn on the back of their hand in cold blue wax.",
              alternatives: ["talk", "hide", "grab the crate and run downhill"],
              rewards: ["the crate", "a sight of the barrow mouth Corvane retreats into"],
            },
          ],
        },
        {
          id: "a_deep_door",
          name: "The Deep Door",
          purpose: "Show what is under the mine, and give the goblins' oath its meaning.",
          startingState: "Beside the Deep Door the mayor's diggers broke into an old barrow tunnel. The dead work at the door from the far side and have it nearly loose.",
          objective: "Find out what is behind the Deep Door, and keep it shut.",
          conflict: "The mine is dark, half flooded and riddled with careless digging; the dead are pushing; the goblins help only if the oath means something to the player.",
          npcs: ["npc_grukka", "npc_pell"],
          locations: ["loc_upper_mine", "loc_lower_mine"],
          clues: [
            {
              id: "cl_door_carvings",
              text: "Around the Deep Door: a bell, a goblin hand and a human hand, and a crowned king lying down. Beneath: 'Rung below, he sleeps. Lit above, he rises. Who wears it, keeps it, cold.'",
              source: "the Deep Door",
              pointsTo: ["t_oath_seal", "t_bell_rite", "t_crown_price"],
            },
            {
              id: "cl_fresh_digging",
              text: "Picks, a lantern from the mayor's hall and a ledger of silver weights, left in the miners' breach.",
              source: "the lower workings",
              pointsTo: ["t_mayor_selling_silver"],
              sets: ["evidence_against_mayor"],
            },
            {
              id: "cl_boy_prints",
              text: "A boy's boot prints going through the gap at the Deep Door's edge, bony footprints either side.",
              source: "the floor by the Deep Door",
              pointsTo: ["t_tam_below"],
              sets: ["barrow_way_found"],
            },
          ],
          approaches: ["go down with goblin guides", "go down alone", "bring Pell's reading of the carvings", "brace the door with timber and stone", "open it", "slip through the gap"],
          outcomes: [
            {
              id: "o_door_held",
              text: "The player, with the Hollow Teeth or alone, braces the Deep Door so the dead cannot push it open.",
              sets: ["deep_door_held"],
              attitudes: [{ id: "f_hollow_teeth", attitude: "friendly" }],
            },
            {
              id: "o_door_opened",
              text: "The player opens the Deep Door from the mine side.",
              sets: ["barrow_way_found", "door_opened_by_player"],
              attitudes: [{ id: "f_hollow_teeth", attitude: "unfriendly" }],
            },
            {
              id: "o_door_passed",
              text: "The player slips through the gap into the barrow halls.",
              sets: ["barrow_way_found"],
            },
          ],
          rewards: ["the way into the barrow from below", "the goblins' respect", "the carvings' warning about the crown"],
          failure: "Unbraced, the door breaks on the villain's schedule.",
          worldChanges: ["whether the dead can come up through the mine", "whether the goblins keep their home"],
          scenes: [
            {
              id: "s_lower_workings",
              name: "The lower workings",
              location: "loc_lower_mine",
              situation: "Ladders down a cold shaft into ankle-deep water, fresh pick marks into an older, smoother tunnel, and at its end the Deep Door, shifting slightly, a hand's width of dark at its edge. Something on the other side is pushing.",
              npcsPresent: [],
              whatTheyWant: "The dead want the door open.",
              playerKnows: "There is a seal down here the goblins guard.",
              hidden: "The door is held only by its own weight now; two skeletons work at it from the far side.",
              interactions: ["read the carvings", "brace the door", "look through the gap", "squeeze through", "listen"],
              checks: [
                { skill: "Religion", dc: 12, reveals: "the carvings, in full" },
                { skill: "Athletics", dc: 14, reveals: "the door braced alone (DC 10 with goblin help)" },
                { skill: "Perception", dc: 11, reveals: "two sets of bony fingers at the gap" },
              ],
              combat: "e_door_breach",
              escalation: "Left unbraced, the door grinds a little wider each turn, then the skeletons come through.",
              outcomes: ["the door is held", "the door is opened", "the player goes through"],
            },
          ],
          encounters: [
            {
              id: "e_door_breach",
              name: "Through the gap",
              type: "combat",
              difficulty: "medium",
              location: "loc_lower_mine",
              participants: ["two skeletons"],
              environment: "A narrow tunnel, ankle-deep water, the door half open behind them.",
              objective: "Push them back and shut the door, or get past.",
              special: ["only one skeleton at a time fits through the gap", "goblin allies who came hold the shaft and fight beside the player"],
              enemyBehavior: "One at a time, silent, never retreating.",
              triggers: ["the door grinds open", "the player squeezes through"],
              success: "The door can be shut and braced.",
              failure: "If the player goes down and lives, the dead drag them through, and they wake in the barrow halls beside a humming boy with a lantern pole.",
              alternatives: ["brace the door before they reach it", "retreat up the shaft and let the goblins hold it"],
              rewards: ["the door shut", "goblin respect"],
            },
          ],
        },
      ],
    },
    {
      id: "act_unburied_king",
      title: "Act III: The Unburied King",
      goal: "Stop the Ember Crown being lit, and bring Tam home.",
      conflict: "Corvane is in the barrow with every dead thing on the ridge between him and the player, and his reason is one the player may not be able to argue with.",
      revelation: "The crown cannot give Corvane what he wants, and whoever wears it becomes the next unburied king.",
      transition: "The player is going under the ridge, and Corvane knows it. The halls are thick with the dead, Tam carries the lantern pole, and the crown waits on a dead king's head to be lit.",
      beats: [
        {
          id: "b_crown_truth",
          text: "The player learns what the crown really does.",
          required: "The inscription, the carvings, Tam, Pell, or the king himself.",
          canHappenThrough: ["the tomb inscription", "the Deep Door carvings", "Tam's half-woken words", "Pell", "King Orrin, if he wakes"],
          result: "The player holds the one argument that might reach Corvane, and a reason never to wear the crown.",
        },
        {
          id: "b_face_to_face",
          text: "The player and Corvane talk, face to face, before it ends.",
          required: "A real conversation, however short, before the last fight or choice.",
          canHappenThrough: ["in the halls", "in the tomb", "at the cairn, if they never met", "with a blade at his throat"],
          result: "Whatever happens next happens to a person, not a monster.",
        },
        {
          id: "b_its_over",
          text: "The confrontation in the tomb is over, one way or another.",
          required: "The tomb scene has settled (lantern out, king asleep, Corvane stopped, or the crown on someone's head) and the moment has passed.",
          canHappenThrough: ["the player walking out of the tomb", "the last enemy falling", "Corvane sitting down beside the bier", "the crown settling"],
          notBefore: { anyOf: ["corvane_stopped", "lantern_destroyed", "king_at_rest", "player_crowned"] },
          result: "The campaign reaches its ending.",
        },
      ],
      arcs: [
        {
          id: "a_barrow_halls",
          name: "The Barrow Halls",
          purpose: "The descent: dread, the dead, and Tam.",
          startingState: "Tam walks the halls with a lantern pole, lighting the way for the dead.",
          objective: "Reach the king's tomb, and free Tam if they can.",
          conflict: "The halls are full of the Lamplighter's dead, and Tam is under his hold.",
          npcs: ["npc_tam", "npc_corvane", "npc_pell", "npc_grukka"],
          locations: ["loc_barrow_halls"],
          clues: [
            {
              id: "cl_corvane_journal",
              text: "On the coffin lid he uses as a desk, Corvane's journal: two years of entries to 'my Lise', the last reading 'Tonight, or the next. I will hear you laugh again.'",
              source: "Corvane's camp in the barrow halls",
              pointsTo: ["t_corvane_daughter", "t_silver_given"],
            },
            {
              id: "cl_tam_words",
              text: "Tam, half woken, whispering that the cold man talks to a little painted portrait every night, and that the crown 'is so cold, it makes him sad'.",
              source: "Tam, once his trance breaks or he is calmed",
              pointsTo: ["t_corvane_daughter", "t_crown_price"],
            },
          ],
          approaches: ["sneak through", "fight through", "follow Tam, who walks to Corvane", "ring the Quiet Bell along the way, if they brought it", "come in from both sides with the goblins"],
          outcomes: [
            {
              id: "o_tam_freed",
              text: "Tam is woken from the trance and sent home, or brought along.",
              sets: ["tam_freed"],
              attitudes: [{ id: "npc_wenna", attitude: "allied" }],
            },
            {
              id: "o_tomb_reached",
              text: "The player reaches King Orrin's tomb.",
              sets: ["tomb_reached"],
            },
          ],
          rewards: ["Tam's life", "Wenna's gratitude for the rest of her days", "the truth of Corvane's grief"],
          failure: "Left under the hold, Tam stands beside Corvane at the end with the lantern pole, and the dead protect him.",
          worldChanges: ["whether Tam goes home"],
          scenes: [
            {
              id: "s_halls_of_niches",
              name: "The halls of niches",
              location: "loc_barrow_halls",
              situation: "Down the middle of a long, low hall of bones walks a boy with an unlit lantern pole, humming, two skeletons behind him.",
              npcsPresent: ["npc_tam"],
              whatTheyWant: "Tam walks to the tomb to light Corvane's way; the skeletons protect him.",
              playerKnows: "Tam is missing. This may be him.",
              hidden: "The trance breaks if he hears his mother's name and is shaken awake, if the Quiet Bell rings near him, or if the lantern goes out.",
              interactions: ["call to him", "follow him", "grab him", "deal with the skeletons", "hide"],
              checks: [
                { skill: "Persuasion", dc: 13, reveals: "Tam hears his mother's name and stops humming" },
                { skill: "Stealth", dc: 12, reveals: "following unseen to the tomb" },
                { skill: "Medicine", dc: 13, reveals: "the trance is not hurting him, and fear will not break it" },
              ],
              combat: "e_hall_guard",
              escalation: "Seen, the player watches Tam walk on as the skeletons turn.",
              outcomes: ["Tam is freed", "Tam leads the player to Corvane"],
            },
          ],
          encounters: [
            {
              id: "e_hall_guard",
              name: "Tam's escort",
              type: "combat",
              difficulty: "medium",
              location: "loc_barrow_halls",
              participants: ["two skeletons"],
              environment: "A long low hall; niches for cover and hiding; no room to swing a long weapon freely.",
              objective: "Get Tam away from them, or get past.",
              special: ["the skeletons never attack Tam", "once his trance breaks, they ignore him and come for the player"],
              enemyBehavior: "They stay between the player and the boy and follow him if he walks on.",
              triggers: ["the player is seen", "the player grabs Tam"],
              success: "Tam is free, or the way to the tomb is clear.",
              failure: "If the player goes down and lives, they are carried to the tomb and laid at Corvane's feet, and he apologises.",
              alternatives: ["break Tam's trance first", "sneak past and follow"],
              rewards: ["Tam", "the way to the tomb"],
            },
          ],
        },
        {
          id: "a_lamplighter",
          name: "The Lamplighter",
          purpose: "The confrontation, and the choice.",
          startingState: "King Orrin lies crowned on his bier under a cold blue light. Corvane kneels at its head with the Grave Lantern, reading the rite aloud. Two skeletons guard the steps.",
          objective: "Stop the crown being lit.",
          conflict: "Corvane will not stop for force alone, the dead will not stop while the lantern burns, and the crown offers the player what it offers him.",
          npcs: ["npc_corvane", "npc_orrin", "npc_tam"],
          locations: ["loc_kings_tomb"],
          clues: [
            {
              id: "cl_tomb_inscription",
              text: "Around Orrin's bier: 'The crown calls back the body and never the breath. Who wears it, keeps it, cold.'",
              source: "the bier in the king's tomb",
              pointsTo: ["t_crown_price"],
            },
          ],
          approaches: ["fight the guard and take the lantern", "smash or snuff the lantern", "ring the Quiet Bell over the king", "talk Corvane down with what the crown really does and what Lise would have wanted", "take the crown first", "let him finish, and face the king"],
          outcomes: [
            {
              id: "o_corvane_let_go",
              text: "Talked out of it, Corvane puts the lantern out himself.",
              sets: ["corvane_stopped", "lantern_destroyed"],
              attitudes: [{ id: "npc_corvane", attitude: "friendly" }],
            },
            {
              id: "o_corvane_stopped",
              text: "Corvane is killed, captured or driven off.",
              sets: ["corvane_stopped"],
            },
            {
              id: "o_lantern_destroyed",
              text: "The Grave Lantern is smashed or snuffed, and the dead fall still.",
              sets: ["lantern_destroyed"],
            },
            {
              id: "o_king_at_rest",
              text: "The Quiet Bell rings in the tomb, and King Orrin sleeps again, for good.",
              sets: ["king_at_rest"],
            },
            {
              id: "o_player_crowned",
              text: "The player puts on the Ember Crown.",
              sets: ["player_crowned"],
            },
          ],
          rewards: ["Blackstone's future", "whatever Corvane leaves behind"],
          failure: "If the player flees the tomb, the clock runs on and the king wakes.",
          worldChanges: ["the ending"],
          scenes: [
            {
              id: "s_the_tomb",
              name: "The king's tomb",
              location: "loc_kings_tomb",
              situation: "Corvane kneels reading at the bier's head, the lantern burning blue beside him, two skeletons on the steps. The crown on the dead king's head has begun, very faintly, to glow.",
              npcsPresent: ["npc_corvane", "npc_orrin"],
              whatTheyWant: "Corvane wants five more minutes. The dead want the rite finished.",
              playerKnows: "This is where it ends.",
              hidden: "Corvane half suspects the crown cannot give him Lise and has not let himself read the inscription on the bier.",
              interactions: ["speak to Corvane", "attack the guard", "go for the lantern", "ring the bell", "read the inscription aloud", "take the crown"],
              checks: [
                { skill: "Religion", dc: 12, reveals: "the inscription on the bier" },
                { skill: "Persuasion", dc: 18, reveals: "Corvane lets go; each piece of evidence shown him lowers it by 2" },
                { skill: "Sleight of Hand", dc: 13, reveals: "the lantern snuffed while he holds it" },
              ],
              combat: "e_tomb_fight",
              escalation: "Each turn the rite goes on, the crown glows brighter; after several turns of nothing, the king's fingers move.",
              outcomes: ["Corvane lets go", "Corvane is stopped", "the lantern goes out", "the king sleeps", "the crown is taken"],
            },
          ],
          encounters: [
            {
              id: "e_tomb_fight",
              name: "The Lamplighter's last guard",
              type: "combat",
              difficulty: "hard",
              location: "loc_kings_tomb",
              participants: ["two skeletons", "Corvane Ash, who does not fight and holds the lantern"],
              environment: "A round chamber, steps down from the halls, the bier at its centre, cold enough to see breath.",
              objective: "Reach the lantern or the king, or stop Corvane.",
              special: [
                "while the lantern burns, one fallen skeleton stands again at the start of the next round, once",
                "snuffing or smashing the lantern is a check, once the player is beside Corvane",
                "ringing the Quiet Bell takes an action and drops every skeleton where it stands",
              ],
              enemyBehavior: "The skeletons hold the steps and guard the lantern. Corvane keeps reading and backs away from violence.",
              npcBehavior: "Tam, if here and entranced, holds up the lantern pole and nothing else.",
              triggers: ["the player attacks", "the player goes for the lantern"],
              success: "The lantern is out or the guard down, and Corvane is alone.",
              failure: "If the player goes down and lives, they watch Corvane finish the rite, and the king sits up.",
              alternatives: ["talk", "ring the bell", "read him the inscription"],
              rewards: ["the end of it"],
            },
            {
              id: "e_corvane_talk",
              name: "Lise's father",
              type: "social",
              difficulty: "hard",
              location: "loc_kings_tomb",
              participants: ["Corvane Ash"],
              environment: "The tomb, the cold light, the crowned king between them.",
              objective: "Make him let go.",
              special: ["each true thing shown him (the journal, the inscription, Tam's words, Pell's account) makes him easier to reach"],
              npcBehavior: "He listens, because he was a scholar first. He will not stop for threats.",
              triggers: ["the player speaks to him instead of attacking"],
              success: "He puts the lantern out himself, sits down beside the bier and weeps.",
              failure: "He turns back to the rite, and the skeletons step forward.",
              alternatives: ["fight", "ring the bell while he talks"],
              rewards: ["Corvane alive, and the lantern out"],
            },
          ],
        },
      ],
    },
  ],

  endings: [
    {
      id: "end_cold_crown",
      title: "The Cold Crown",
      when: { allOf: ["player_crowned", "b_its_over"] },
      text: "The crown is on the player's head and the dead kneel. Play the cold coming in: the power is real, the price has begun, and whoever is near looks at them as they once looked at Corvane. End on the player choosing what to command first.",
    },
    {
      id: "end_fallen",
      title: "The Unburied King",
      when: { allOf: ["c_king_wakes"] },
      text: "King Orrin is awake and crowned, and the dead walk down the valley. Blackstone cannot be saved tonight. Play the flight from the village, let the player save who they can, and make it plain the valley road is the king's now.",
    },
    {
      id: "end_dawn",
      title: "Dawn over Blackstone",
      when: { allOf: ["king_at_rest", "b_its_over"] },
      text: "The king sleeps for good and the dead are still. Play the walk out at dawn: who waits at the top of the ridge, what the village does with its mayor, what Grukka says about the oath, whether Wenna gets her son back.",
    },
    {
      id: "end_quiet_ridge",
      title: "A Quiet Ridge",
      when: { allOf: ["b_its_over"] },
      text: "The lantern is out and the dead lie down, but King Orrin still wears his crown in an unsealed tomb. Over for now. Play the return and let the ridge feel unfinished: one day someone will light that crown again, unless the Quiet Bell is brought down to ring over him.",
    },
  ],

  dmNotes: [
    "Pitch fights for one character, levels 1 to 3: two goblins or two skeletons is hard at level 1, so drop one enemy then.",
    "Goblins take prisoners and the dead drag the fallen to their master: once the player is down, enemies stop attacking them. Death saves are still the dice's.",
    "The goblins are not the threat. Let the player find that out; never tell them.",
    "Nobody is simply evil: Venn is a frightened man doing a cowardly thing, Snik a boy playing warrior, Corvane a father. Show it without excusing anyone.",
    "Dread at night, warmth by day: daylight in the village should feel worth saving.",
    "The ledger, the letters, the Quiet Bell and the journal are ordinary things, never magic items. To make one pocketable, put it on a prop with grantsItem; if someone hands one over, record it in memoryFacts as an item.",
    "The clock is the engine's: never fire or announce a step. When a STORY, OFFSCREEN note arrives, let the player meet it as a person would: a rumour, a scream in the night, a door that was shut and is not.",
  ],
};
