/**
 * The Quiet Under Blackstone: the first written campaign, and the worked
 * example of the format (CAMPAIGN_TEMPLATE.md walks a writer through the same
 * fields, blank).
 *
 * Fantasy, three acts, sized for one character between levels 1 and 3, built
 * only from creatures the rules engine has real numbers for (goblins and
 * skeletons) and NPC tokens the roster already draws. Every encounter's
 * "failure" assumes the character went down and lived: goblins take
 * prisoners and the dead drag the fallen to their master, so a lost fight
 * moves the story somewhere worse rather than ending it. The death saves are
 * still the dice's.
 *
 * The map, in cells (north is up, cy-1):
 *
 *            cx -1          cx 0              cx 1
 *   cy -4                   king's tomb
 *   cy -3    the cairn      barrow halls      lower mine (Deep Door)
 *   cy -2    barrow-field   goblin camp       upper mine
 *   cy -1    barrow-field   old mine road
 *   cy  0    shrine         the square        mayor's house
 *   cy  1                   carter's yard
 *
 * Ids are permanent once this has been played (see campaign/types.ts).
 */
import type { CampaignModule } from "../types";

export const BLACKSTONE: CampaignModule = {
  id: "blackstone",
  version: 1,
  template: "fantasy",

  premise: {
    title: "The Quiet Under Blackstone",
    tone: "Folk horror with a warm centre: dread in the dark, small kindnesses by day, and nobody in it simply evil, the villain included.",
    setting:
      "Blackstone, a played-out silver-mining village of about sixty people in a cold valley four days from the nearest town. On the ridge above it lies the barrow-field, the grassed-over graves of the kings of a kingdom that fell centuries ago. Above the village is the old mine, held for three generations by a goblin clan under an oath nobody in the village talks about.",
    centralConflict:
      "A grieving scholar is waking the dead king buried beneath the ridge so that he can use the king's crown, and Blackstone's own mayor has been selling him the grave-silver to do it, without knowing what it is for.",
    hook: "Three people have vanished from Blackstone in two weeks, and the village says the goblins took them. The mayor is offering a reward. Up on the ridge, at night, something walks that is not a goblin.",
    bigQuestion: "Who is waking the dead under Blackstone, and what does he want them for?",
    endState: {
      success:
        "The king sleeps again, the scholar is stopped or lets go of his grief, the goblins and the village have a new oath, Tam Holt goes home to his mother, and Blackstone lives to see the spring.",
      failure:
        "The Ember Crown is lit, King Orrin wakes, and every grave on the ridge empties. The dead walk down the valley road, and Blackstone is the first village they reach.",
    },
  },

  start: {
    location: "loc_square",
    situation:
      "Dusk in the village square. A fresh notice on the board by the well names the third missing person, Tam Holt. Mayor Venn is reading it aloud to a small, angry crowd and promising a reward to whoever brings the goblins to heel. The player has just walked in on the valley road.",
  },

  truths: [
    {
      id: "t_three_missing",
      visibility: "known",
      text: "Three villagers have vanished in two weeks: Bessa Crane, the miller's daughter; old Jory Flint, a retired miner; and Tam Holt, the carter's fifteen-year-old son.",
    },
    {
      id: "t_goblins_near",
      visibility: "known",
      text: "A goblin clan, the Hollow Teeth, has lived in the old mine above the village for longer than anyone alive can remember. Villagers rarely see them.",
    },
    {
      id: "t_mine_played_out",
      visibility: "known",
      text: "The silver ran out of the Blackstone mine a year ago, and the village has been getting poorer ever since.",
    },
    {
      id: "t_barrow_field",
      visibility: "known",
      text: "The ridge above the village is the barrow-field, the graves of the old kings. Nobody goes up there, and children are told it is bad luck to point at it.",
    },
    {
      id: "t_grain_toll",
      visibility: "discoverable",
      text: "Since Blackstone was founded, the village has paid the Hollow Teeth a grain toll every season, and in return the goblins guard the bottom of the mine. Mayor Venn stopped paying three months ago, to save money.",
      learnedVia: ["the village tithe ledger in the mayor's study", "Grukka or any Hollow Teeth goblin", "Sexton Pell, who remembers the old terms", "Wenna Holt, who used to haul the grain"],
    },
    {
      id: "t_goblins_took_two",
      visibility: "discoverable",
      text: "The Hollow Teeth took Bessa and Jory as surety for the unpaid toll. Both are alive, fed, unhurt and bored, roped under an awning in the goblin camp.",
      learnedVia: ["the tracks from the mill to the old mine road", "the goblin camp itself", "Grukka", "a captured or befriended goblin"],
    },
    {
      id: "t_mayor_selling_silver",
      visibility: "discoverable",
      text: "Mayor Venn has been selling grave-silver to a buyer he has never met. His men dug it out of the bottom of the mine, where the workings broke into the old barrow tunnels, and Wenna Holt carts it up to the cairn on the ridge where the buyer leaves payment in old royal coin.",
      learnedVia: ["the buyer's letters in the mayor's locked desk", "Wenna Holt", "Grukka, whose goblins watched the digging", "the abandoned picks and weight ledger in the lower mine"],
      sets: ["evidence_against_mayor"],
    },
    {
      id: "t_dead_walk_ridge",
      visibility: "discoverable",
      text: "Skeletons walk the barrow-field at night. They do not come down into the village. Yet.",
      learnedVia: ["watching the ridge after dark", "Hobb the watchman, who has seen them twice and told nobody", "Sexton Pell"],
    },
    {
      id: "t_lantern_mark",
      visibility: "discoverable",
      text: "The buyer signs every letter with a small drawn lantern, and collects the silver from the cairn at the top of the barrow-field at midnight.",
      learnedVia: ["the buyer's letters", "Wenna Holt", "watching the cairn at night"],
    },
    {
      id: "t_tam_below",
      visibility: "discoverable",
      text: "Tam Holt was not taken by goblins. Curious about his mother's heavy crates, he went down into the bottom of the mine alone, and the dead took him to the Lamplighter, who keeps him entranced as a lamp-bearer. He is alive.",
      learnedVia: ["Grukka, whose sentries saw him go down", "a boy's boot prints by the Deep Door", "a glimpse of a boy carrying a lantern pole beside the dead", "finding him in the barrow halls"],
    },
    {
      id: "t_oath_seal",
      visibility: "discoverable",
      text: "The goblins' oath was never really about the mine. The Hollow Teeth keep the Deep Door shut: the round stone seal between the bottom of the mine and the barrow halls under the ridge, so that nothing buried there can come down through the mine into the valley. The village's grain was their wage, sworn long ago to the keepers of the Quiet Bell.",
      learnedVia: ["Sexton Pell", "Grukka, once she trusts the player", "the carvings on the Deep Door", "the oath stone in the goblin camp"],
    },
    {
      id: "t_silver_given",
      visibility: "discoverable",
      text: "Grave-silver only holds the Lamplighter's cold flame if living hands give it. Stolen, it will not burn. That is why he buys it instead of digging it himself, and why cutting off the mayor's silver slows him down.",
      learnedVia: ["Sexton Pell", "Corvane's journal", "studying the Grave Lantern (Arcana)"],
    },
    {
      id: "t_corvane_is_buyer",
      visibility: "secret",
      text: "The buyer is Corvane Ash, a royal archivist from the capital who left in disgrace. He is the Lamplighter, and the dead on the ridge answer to his Grave Lantern.",
      learnedVia: ["meeting him at the cairn", "the scratched-out archive seal on his payment purse", "Tam, once woken", "Corvane himself"],
      revealWhen: { allOf: ["act:act_silver_road"] },
    },
    {
      id: "t_corvane_daughter",
      visibility: "secret",
      text: "Corvane's daughter Lise died of a winter fever two years ago while he was away in the archives. He believes the Ember Crown, which commands the dead, will let him call her back. It will not: it calls back the body and never the person.",
      learnedVia: ["Corvane's journal in the barrow halls", "Tam, half-woken", "Corvane himself, if the player earns his trust", "Sexton Pell, who knows what the crown does"],
      revealWhen: { allOf: ["t_corvane_is_buyer"] },
    },
    {
      id: "t_crown_price",
      visibility: "secret",
      text: "Whoever wears the Ember Crown commands the dead, and slowly becomes one of them: the crown takes its wearer's warmth until they are the next unburied king.",
      learnedVia: ["the inscription on King Orrin's tomb", "the carvings on the Deep Door, read in full", "Sexton Pell's grandmother's account", "King Orrin himself, if he wakes"],
      revealWhen: { anyOf: ["act:act_silver_road", "act:act_unburied_king"] },
    },
    {
      id: "t_bell_rite",
      visibility: "secret",
      text: "The Quiet Bell, a fist-sized hand bell of dark bronze hanging over the shrine's altar where everyone takes it for decoration, was cast to lay King Orrin to rest. Rung in his tomb, it puts every dead thing in the barrow back to sleep, and its sound breaks the Lamplighter's hold on Tam.",
      learnedVia: ["Sexton Pell, once she trusts the player", "the bell's own inscription, read with Religion"],
      revealWhen: { anyOf: ["pell_trusts_player", "cl_bell_inscription"] },
    },
  ],

  villain: {
    npc: "npc_corvane",
    goal: "Light the Ember Crown on the head of King Orrin, and use its command over the dead to call his daughter Lise back.",
    motivation: "Grief, and guilt. Lise died while he was away chasing a footnote in the archives, and he has not forgiven himself for a single day since.",
    plan: "Buy grave-silver from Blackstone's mayor, forge the Grave Lantern from it, use the lantern's cold light to raise the barrow's dead as his servants, wake King Orrin in his tomb under the ridge, and light the crown.",
    resources: ["the Grave Lantern, nearly finished", "the skeletons of the barrow-field, which obey whoever holds the lantern", "Tam Holt, entranced, as a lamp-bearer", "a purse of old royal coin", "two years of reading about this one rite"],
    allies: ["the dead, through the lantern", "Mayor Venn, without knowing it"],
    weakness: "The Grave Lantern. Without it the dead stop obeying him and he is a frail man alone in a cold tomb. It can be smashed, snuffed, or drowned out by the Quiet Bell.",
    limitations: [
      "he is no fighter and avoids being seen",
      "the dead obey the lantern and not him, and they will not leave the barrow-field or the barrow halls while the Deep Door holds",
      "the lantern only burns on silver that living hands give him, and the mayor's is the only silver left in the valley",
    ],
    status: "Living in the barrow halls beneath the ridge, coming up through the cairn at midnight to collect the mayor's silver. The lantern is nearly finished.",
    clock: [
      {
        id: "c_ridge_walkers",
        when: { afterScene: 12 },
        event: "A shepherd sees two skeletons walking the barrow-field at dusk and runs into the village screaming. Blackstone blames goblin witchcraft, and the talk in the square turns to a raid on the mine.",
        sets: ["village_wants_raid"],
      },
      {
        id: "c_lantern_finished",
        when: { afterScene: 30 },
        preventedBy: { anyOf: ["silver_cut_off"] },
        event: "Corvane finishes the Grave Lantern with the last of the mayor's silver. Its cold light wakes every grave on the ridge, and the dead begin to gather in the barrow halls.",
        sets: ["lantern_finished"],
      },
      {
        id: "c_silver_taken",
        when: { allOf: ["prevented:c_lantern_finished"], afterScene: 42 },
        preventedBy: { anyOf: ["corvane_stopped", "lantern_destroyed"] },
        event: "Starved of silver, Corvane comes down into Blackstone himself one night with his dead at his back and has the terrified mayor give him the shrine's silver candlesticks. Frightened hands still count as living ones. The lantern is finished, late.",
        sets: ["lantern_finished"],
      },
      {
        id: "c_door_breaks",
        when: { allOf: ["lantern_finished"], afterScene: 45 },
        preventedBy: { anyOf: ["deep_door_held", "corvane_stopped", "lantern_destroyed"] },
        event: "The dead break the Deep Door from the barrow side and pour up through the mine. The Hollow Teeth are driven out of their warrens and flee down to the edge of the village, where frightened villagers take them for an attack. That night the dead walk into Blackstone, and the shrine is full of people until dawn.",
        sets: ["door_broken"],
      },
      {
        id: "c_king_wakes",
        when: { allOf: ["lantern_finished"], afterScene: 60 },
        preventedBy: { anyOf: ["corvane_stopped", "lantern_destroyed", "king_at_rest"] },
        event: "King Orrin wakes and the Ember Crown is lit. Every grave on the ridge empties at once, and the dead march down the valley road.",
        sets: ["king_woken"],
      },
    ],
  },

  factions: [
    {
      id: "f_village",
      name: "Blackstone village",
      goal: "Survive the winter without the mine.",
      leader: "npc_venn",
      resources: ["about sixty people, few of them fighters", "Hobb the watchman", "the shrine", "the valley road out"],
      allies: ["f_bell"],
      enemies: [],
      attitude: "neutral",
      wantsFromPlayer: "Bring the missing home and make the goblins stop.",
      ifIgnored:
        "The village works itself up to a torch-and-pitchfork raid on the goblin camp. People die on both sides, and the Deep Door goes unguarded while the goblins are fighting.",
    },
    {
      id: "f_hollow_teeth",
      name: "The Hollow Teeth",
      goal: "Keep the oath, feed the clan, and keep what is behind the Deep Door below it.",
      leader: "npc_grukka",
      resources: ["about twenty goblins, eight of them warriors", "the old mine tunnels, which they know in the dark", "the oath, which they take more seriously than the village ever has"],
      allies: ["f_bell"],
      enemies: ["f_lamplighter"],
      attitude: "wary",
      wantsFromPlayer: "The grain toll paid, or the oath honoured some other way, and help against what is scratching at the Deep Door.",
      ifIgnored:
        "They take another villager as surety every few days, and Snik starts talking about taking the grain instead. If the Deep Door breaks, they flee down into the village, which will take it as an attack.",
    },
    {
      id: "f_bell",
      name: "The keepers of the Quiet Bell",
      goal: "Keep the dead asleep, as the keepers promised long ago.",
      leader: "npc_pell",
      resources: ["the Quiet Bell", "the shrine's old records", "one stubborn old woman"],
      allies: ["f_village", "f_hollow_teeth"],
      enemies: ["f_lamplighter"],
      attitude: "wary",
      wantsFromPlayer: "Someone young enough to carry the bell up to the barrow, and willing to believe her.",
      ifIgnored: "Pell tries to climb the ridge alone one night and does not come back. The Quiet Bell is found later, lying in the barrow-field grass.",
    },
    {
      id: "f_lamplighter",
      name: "The Lamplighter's dead",
      goal: "Wake King Orrin and light the Ember Crown.",
      leader: "npc_corvane",
      resources: ["the Grave Lantern", "the skeletons of the barrow-field", "Tam Holt, entranced"],
      allies: [],
      enemies: ["f_hollow_teeth", "f_bell"],
      attitude: "hostile",
      wantsFromPlayer: "To be left alone, or for the player to stand aside.",
      ifIgnored: "The villain's clock runs out.",
    },
  ],

  npcs: [
    {
      id: "npc_venn",
      name: "Aldous Venn",
      role: "mayor of Blackstone",
      description: "A heavy, careful man in a good coat gone shiny at the elbows. He keeps his chain of office polished.",
      personality: "Proud and anxious, generous in public and mean with the truth.",
      motivation: "Blackstone's survival, and his own standing in it: he could not bear to be the mayor who let the village die.",
      fears: "Being found out; the village emptying; the goblins coming for him personally.",
      values: "Order, appearances, the village's good name.",
      secrets: ["t_grain_toll", "t_mayor_selling_silver", "t_lantern_mark"],
      knowledge: [
        "the terms of the grain toll, as he chose to understand them",
        "how much silver has gone up the ridge on Wenna's cart, and what it paid",
        "that the buyer pays in old royal coin and writes like a scholar",
      ],
      relationships: ["leans on Wenna Holt, who owes him money", "dismisses Sexton Pell as a superstitious old woman", "Hobb the watchman answers to him"],
      attitude: "neutral",
      speech: "Over-formal and full of civic phrases. Answers questions about money with questions about safety.",
      currentGoal:
        "Keep the disappearances blamed on the goblins until the buyer's last payment comes in, then pay the village's debts and never dig again.",
      faction: "f_village",
      location: "loc_mayors_house",
      token: "token_villager",
    },
    {
      id: "npc_hobb",
      name: "Hobb Varley",
      role: "Blackstone's only watchman",
      description: "A broad young man in a borrowed breastplate that does not fit, with a spear he has never used on anything but rats.",
      personality: "Honest, easily embarrassed, braver than he thinks he is.",
      motivation: "Do right by the village.",
      fears: "The ridge at night; letting the mayor down.",
      values: "Duty, his neighbours.",
      secrets: ["t_dead_walk_ridge"],
      knowledge: [
        "he has seen two skeletons on the ridge at dusk, twice, and was told by the mayor to stop talking about ghosts",
        "he found goblin tracks at the mill and was told to leave them be",
        "Sexton Pell has been trying to tell people something for weeks",
      ],
      relationships: ["answers to the mayor", "sweet on Bessa Crane, one of the missing", "fond of Pell, who taught him his letters"],
      attitude: "friendly",
      speech: "Says sir or ma'am to everyone, and rambles when he is nervous.",
      currentGoal: "Find the missing three without having to go up the ridge in the dark.",
      faction: "f_village",
      location: "loc_square",
      token: "token_guard",
    },
    {
      id: "npc_wenna",
      name: "Wenna Holt",
      role: "the village carter, Tam's mother",
      description: "A wiry woman with rope-burned hands and a cart she cannot stop fixing.",
      personality: "Hard-working, frightened, and angry at herself.",
      motivation: "Get her son back.",
      fears: "That the crates she carried are why Tam is gone.",
      values: "Her family; paying what she owes.",
      secrets: ["t_mayor_selling_silver", "t_lantern_mark"],
      knowledge: [
        "she has hauled six heavy, sealed crates from the mine to the cairn on the ridge, for the mayor, at night",
        "Tam asked her what was in the crates the day before he vanished",
        "she used to haul the goblins' grain, until the mayor stopped it",
      ],
      relationships: ["owes Mayor Venn a debt she cannot pay", "Tam's mother", "friendly with Hobb"],
      attitude: "neutral",
      speech: "Short and plain. Swallows her words when the mayor is near.",
      currentGoal: "Find Tam without telling anyone about the crates, because the mayor said that would ruin her.",
      faction: "f_village",
      location: "loc_carters_yard",
      token: "token_villager",
    },
    {
      id: "npc_pell",
      name: "Ilse Pell",
      role: "sexton of the shrine of the Quiet Bell",
      description: "A small, sharp old woman with ink-stained fingers and a ring of iron keys at her belt.",
      personality: "Stubborn and dry, kind under the sharpness, tired of not being listened to.",
      motivation: "Keep the promise her family made to the dead.",
      fears: "That the rite has been forgotten, and that she is too old to perform it herself.",
      values: "Rest for the dead, honesty, the old courtesies.",
      secrets: ["t_oath_seal", "t_silver_given", "t_bell_rite", "t_crown_price"],
      knowledge: [
        "the old terms of the goblins' oath",
        "King Orrin's name, and that he was buried crowned",
        "the rite of the Quiet Bell, from her grandmother",
        "that the crown takes the wearer's warmth",
      ],
      relationships: ["respects Grukka, whose grandmother swore the oath to hers", "despairs of Mayor Venn", "taught Hobb his letters"],
      attitude: "wary",
      speech: "Clipped and dry. Quotes old rhymes and answers questions with questions.",
      currentGoal: "Find someone who will believe her and carry the Quiet Bell up to the barrow, since her knees will not.",
      faction: "f_bell",
      location: "loc_shrine",
      token: "token_robed_figure",
    },
    {
      id: "npc_grukka",
      name: "Grukka Two-Knives",
      role: "chief of the Hollow Teeth",
      description: "A grey-skinned goblin with a notched ear and two mismatched knives at her belt, older than most goblins live to be.",
      personality: "Blunt, patient, dryly funny, and never bluffing.",
      motivation: "Her clan's survival and its honour: the oath is the one thing that makes the Hollow Teeth more than vermin in the village's eyes.",
      fears: "What is waking behind the Deep Door; her young warriors dying for a village that cheats them.",
      values: "Oaths kept, debts paid, children fed.",
      secrets: ["t_goblins_took_two", "t_tam_below", "t_oath_seal"],
      knowledge: [
        "the mayor stopped the grain and sent men to dig at the bottom of the mine",
        "her sentries saw a village boy go down the shaft alone and not come back",
        "something has been scratching at the Deep Door from the far side for a month",
      ],
      relationships: ["despises Mayor Venn as an oath-breaker", "respects Sexton Pell", "her nephew Snik is the clan's hothead"],
      attitude: "wary",
      speech: "Short sentences in trader's village-speech. Calls the player walker.",
      currentGoal: "Get the grain toll paid, or something worth as much, before her clan starves or the Deep Door gives.",
      faction: "f_hollow_teeth",
      location: "loc_goblin_camp",
      token: "token_goblin",
    },
    {
      id: "npc_snik",
      name: "Snik",
      role: "Grukka's nephew, the youngest Hollow Teeth warrior",
      description: "A wiry young goblin with too many knives and a shield painted with a grinning mouth.",
      personality: "Loud, proud, reckless, and desperate to be taken seriously.",
      motivation: "Prove himself a warrior to his aunt and the clan.",
      fears: "Being laughed at; the scratching at the Deep Door, which he will not admit to.",
      values: "Courage as he understands it, which is mostly shouting.",
      secrets: [],
      knowledge: ["where the captives are kept", "the quickest way down the mine"],
      relationships: ["Grukka's nephew", "thinks the village owes the clan blood, not grain"],
      attitude: "hostile",
      speech: "Boasts, challenges, insults the player's shoes.",
      currentGoal: "Raid the village for the unpaid grain and come home a hero.",
      faction: "f_hollow_teeth",
      location: "loc_goblin_camp",
      token: "token_goblin",
    },
    {
      id: "npc_corvane",
      name: "Corvane Ash",
      role: "the Lamplighter, once a royal archivist",
      description:
        "A thin man in a scholar's black coat, grey before his time, carrying a lantern of grey silver that burns with a cold blue flame.",
      personality: "Courteous, precise, exhausted, and utterly certain.",
      motivation: "Bring his daughter Lise back from death.",
      fears: "Being too late; forgetting her face.",
      values: "Knowledge, promises, his daughter.",
      secrets: ["t_corvane_is_buyer", "t_corvane_daughter", "t_silver_given"],
      knowledge: ["the rite that wakes King Orrin", "how the Grave Lantern works", "that the dead obey the lantern and not him", "the history of every king on the ridge"],
      relationships: ["Lise's father", "buys from the mayor through letters and has never met him", "keeps Tam as a lamp-bearer and feeds him carefully"],
      attitude: "wary",
      speech: "Soft, formal and archival. Corrects people's history. Never raises his voice.",
      currentGoal: "Finish the Grave Lantern and light the crown before anyone in the village understands what he is doing.",
      faction: "f_lamplighter",
      location: "loc_barrow_halls",
      token: "token_robed_figure",
    },
    {
      id: "npc_tam",
      name: "Tam Holt",
      role: "the missing carter's son, entranced",
      description: "A gangly fifteen-year-old with a blank, peaceful face, carrying a lantern pole with no light on it.",
      personality: "Cheeky and curious when himself; empty and humming now.",
      motivation: "None while entranced. Once woken, to go home to his mother.",
      fears: "Once woken: the dark, and the cold man.",
      values: "His mother, his mates, a good joke.",
      secrets: [],
      knowledge: ["the way through the barrow halls", "where Corvane sleeps", "that Corvane talks to a small painted portrait every night"],
      relationships: ["Wenna's son", "Corvane's lamp-bearer, for now"],
      attitude: "neutral",
      speech: "Entranced, he hums and says nothing. Woken, he talks too fast and cries.",
      currentGoal: "Carry the lantern pole wherever the Lamplighter walks.",
      faction: "f_lamplighter",
      location: "loc_barrow_halls",
      token: "token_villager",
    },
    {
      id: "npc_orrin",
      name: "King Orrin the Unburied",
      role: "the dead king beneath the ridge",
      description: "A tall skeleton in rotted royal silks on a stone bier, a crown of dark gold on his skull.",
      personality: "Asleep. If woken: cold, regal, and certain the valley is still his.",
      motivation: "To sleep. If woken, to rule again.",
      fears: "The Quiet Bell.",
      values: "Obedience.",
      secrets: ["t_crown_price"],
      knowledge: ["what the crown does to its wearer, because it did it to him"],
      relationships: ["sworn to sleep by the keepers of the Quiet Bell"],
      attitude: "hostile",
      speech: "Asleep, nothing. Woken, very few words, all of them commands.",
      currentGoal: "Sleep.",
      faction: "f_lamplighter",
      location: "loc_kings_tomb",
      token: "token_skeleton",
    },
  ],

  locations: [
    {
      id: "loc_square",
      name: "Blackstone square",
      cells: [{ cx: 0, cy: 0, hint: "the village square: the well, the notice board, the mayor's hall to the east, the shrine to the west" }],
      description: "A cobbled square around a deep stone well, with the notice board, the mayor's hall to the east and the shrine to the west.",
      atmosphere: "By day, a tired village pretending things are normal. At dusk, torches and angry voices.",
      features: ["the well", "the notice board with three names on it", "the road north to the old mine", "the lane south to the carter's yard"],
      npcs: ["npc_hobb", "npc_venn"],
      secrets: ["t_dead_walk_ridge"],
      interactables: ["the notices", "the well", "the crowd"],
      encounters: ["e_crowd"],
      connected: ["loc_mayors_house", "loc_shrine", "loc_carters_yard", "loc_mine_road"],
      threats: ["a crowd that wants someone to blame"],
      discoverable: ["Hobb's account of the ridge", "who in the crowd is frightened and who is angry"],
    },
    {
      id: "loc_mayors_house",
      name: "The mayor's house",
      cells: [{ cx: 1, cy: 0, hint: "the mayor's house and hall: a cold, tidy study upstairs with ledgers and a locked desk" }],
      description: "The best house in Blackstone, with the village hall on its ground floor and the mayor's study above.",
      atmosphere: "Polished, cold and quiet. The hearth in the study is full of burnt paper.",
      features: ["the hall", "the study", "a locked desk", "a cold hearth"],
      npcs: ["npc_venn"],
      secrets: ["t_grain_toll", "t_mayor_selling_silver", "t_lantern_mark"],
      interactables: ["the tithe ledger on the shelf", "the locked desk", "the burnt paper in the hearth"],
      encounters: [],
      connected: ["loc_square"],
      threats: ["being caught by the mayor, who will have Hobb throw the player out of the village"],
      discoverable: ["the tithe ledger", "the buyer's letters", "a lantern mark on a burnt corner of paper"],
    },
    {
      id: "loc_shrine",
      name: "The shrine of the Quiet Bell",
      cells: [{ cx: -1, cy: 0, hint: "the shrine: a cold stone chapel too big for the village, a small bronze bell over the altar, a path north up to the ridge" }],
      description: "A cold stone chapel too big for Blackstone, older than the village. A small dark bronze hand bell hangs on a hook over the altar.",
      atmosphere: "Still and clean. It smells of beeswax and old stone, and it is always colder than outside.",
      features: ["the altar", "the Quiet Bell on its hook", "old carvings of a sleeping king", "the path north up to the barrow-field"],
      npcs: ["npc_pell"],
      secrets: ["t_oath_seal", "t_bell_rite", "t_crown_price", "t_silver_given"],
      interactables: ["the Quiet Bell and its inscription", "the carvings", "the shrine records"],
      encounters: [],
      connected: ["loc_square", "loc_barrow_field"],
      threats: [],
      discoverable: ["the bell's inscription", "the old terms of the oath, in the records"],
    },
    {
      id: "loc_carters_yard",
      name: "Wenna's yard",
      cells: [{ cx: 0, cy: 1, hint: "the carter's yard: a cart, a stable, and a boy's coat still on the peg" }],
      description: "A muddy yard with a stable, a cart and a lean-to house. Tam's coat still hangs on its peg.",
      atmosphere: "Busy hands and an empty doorway.",
      features: ["the cart", "the stable", "Tam's coat"],
      npcs: ["npc_wenna"],
      secrets: ["t_mayor_selling_silver", "t_lantern_mark"],
      interactables: ["the cart bed, which has grey silver dust in it", "a lantern scratched into one board"],
      encounters: [],
      connected: ["loc_square"],
      threats: [],
      discoverable: ["silver dust in the cart", "Wenna's account of the crates"],
    },
    {
      id: "loc_mine_road",
      name: "The old mine road",
      cells: [{ cx: 0, cy: -1, hint: "the old mine road climbing north through pine woods, rutted by carts, with tracks in the mud" }],
      description: "A rutted cart road climbing north from the square through dark pine woods toward the old mine.",
      atmosphere: "Pine-quiet. Things watch from the trees.",
      features: ["the cart ruts", "drag marks in the mud", "a goblin lookout post in a tree"],
      npcs: [],
      secrets: ["t_goblins_took_two", "t_tam_below"],
      interactables: ["the tracks", "the lookout post"],
      encounters: ["e_scout"],
      connected: ["loc_square", "loc_goblin_camp", "loc_barrow_field"],
      threats: ["a goblin scout"],
      discoverable: ["two sets of tracks, one goblin, one a boy's boots walking alone"],
    },
    {
      id: "loc_goblin_camp",
      name: "The Hollow Teeth camp",
      cells: [{ cx: 0, cy: -2, hint: "the goblin camp at the mine mouth: hide tents, old mine timbers, a carved oath stone, and two captives under an awning" }],
      description: "A camp of hide tents and old mine timbers at the mouth of the Blackstone mine, around a carved oath stone.",
      atmosphere: "Watchful and hungry. Half the warriors sleep facing the mine, not the road.",
      features: ["the oath stone", "the captives' awning", "the mine mouth", "the cook fire"],
      npcs: ["npc_grukka", "npc_snik"],
      secrets: ["t_goblins_took_two", "t_oath_seal", "t_tam_below", "t_grain_toll"],
      interactables: ["the oath stone", "the captives' ropes", "the mine mouth"],
      encounters: ["e_parley", "e_camp_fight"],
      connected: ["loc_mine_road", "loc_upper_mine", "loc_barrow_field"],
      threats: ["Snik and two warriors", "a lie Grukka catches"],
      discoverable: ["the meaning of the oath stone", "the goblins' fear of the mine"],
    },
    {
      id: "loc_upper_mine",
      name: "The upper workings",
      cells: [{ cx: 1, cy: -2, hint: "the old mine's upper workings: timbered tunnels, goblin sleeping niches, and a cold draught coming up the shaft" }],
      description: "The old mine's upper tunnels, where the Hollow Teeth live, and the head of the shaft that goes down.",
      atmosphere: "Smoky and close. A cold draught comes up the shaft, and at night, a faint scratching.",
      features: ["goblin sleeping niches", "the shaft head and its ladders", "old ore carts"],
      npcs: [],
      secrets: ["t_oath_seal"],
      interactables: ["the shaft", "the ladders"],
      encounters: [],
      connected: ["loc_goblin_camp", "loc_lower_mine"],
      threats: ["goblins who did not agree to the player being here"],
      discoverable: ["the scratching from below, after dark"],
    },
    {
      id: "loc_lower_mine",
      name: "The lower workings and the Deep Door",
      cells: [{ cx: 1, cy: -3, hint: "the bottom of the mine: ankle-deep water, fresh pick marks, and on the west side a round stone door carved with a bell" }],
      description:
        "The bottom of the mine, half flooded. Fresh pick marks show where the mayor's men broke into older, smoother tunnels. On the west side stands the Deep Door, a round stone seal carved with a bell.",
      atmosphere: "Cold water, dripping, and the sound of something on the far side of the stone.",
      features: ["the Deep Door and its carvings", "the breach the miners dug", "abandoned picks", "a gap a hand wide at the door's edge"],
      npcs: [],
      secrets: ["t_oath_seal", "t_mayor_selling_silver", "t_tam_below", "t_crown_price"],
      interactables: ["the carvings", "the gap", "the abandoned picks and weight ledger", "timbers that could brace the door"],
      encounters: ["e_door_breach"],
      connected: ["loc_upper_mine", "loc_barrow_halls"],
      threats: ["the dead working at the door from the far side"],
      discoverable: ["the carvings", "a boy's boot prints going through the gap"],
    },
    {
      id: "loc_barrow_field",
      name: "The barrow-field",
      cells: [
        { cx: -1, cy: -1, hint: "the lower barrow-field: grassed grave mounds climbing the ridge, standing stones, the path up from the shrine" },
        { cx: -1, cy: -2, hint: "the upper barrow-field: the oldest mounds, wind, and footprints that are not a person's" },
      ],
      description: "Long grassed grave mounds climbing the ridge above the village, with standing stones between them.",
      atmosphere: "Wind and silence by day. At night, a cold blue light moving among the mounds.",
      features: ["grave mounds", "standing stones", "the view down over Blackstone", "bony footprints in the frost"],
      npcs: [],
      secrets: ["t_dead_walk_ridge"],
      interactables: ["the mounds", "the standing stones"],
      encounters: [],
      connected: ["loc_shrine", "loc_mine_road", "loc_goblin_camp", "loc_cairn"],
      threats: ["skeletons walking at night"],
      discoverable: ["the dead walking", "a blue light that moves when they move"],
    },
    {
      id: "loc_cairn",
      name: "The cairn",
      cells: [{ cx: -1, cy: -3, hint: "the cairn at the top of the ridge: a tall stack of black stones, and behind it a barrow mouth recently dug open" }],
      description: "A tall stack of black stones at the top of the ridge, where the buyer leaves payment. Behind it, a barrow mouth has been dug open.",
      atmosphere: "Exposed, windy, and watched.",
      features: ["the cairn", "the dug-open barrow mouth", "a steep drop on the east side"],
      npcs: [],
      secrets: ["t_lantern_mark", "t_corvane_is_buyer", "t_tam_below"],
      interactables: ["the payment niche in the cairn", "the barrow mouth", "lantern soot on the lintel"],
      encounters: ["e_cairn_guard"],
      connected: ["loc_barrow_field", "loc_barrow_halls"],
      threats: ["the Lamplighter's guard of two skeletons, at midnight"],
      discoverable: ["the archive seal on a payment purse", "a boy's boot print in the dust"],
    },
    {
      id: "loc_barrow_halls",
      name: "The barrow halls",
      cells: [{ cx: 0, cy: -3, hint: "the barrow halls under the ridge: low stone halls lined with niches of bones, every third niche empty" }],
      description: "Low stone halls under the ridge, lined with niches of bones, every third niche empty. Corvane has made a camp here on a coffin lid.",
      atmosphere: "Cold, dry and humming: Tam hums as he walks.",
      features: ["niches of bones", "Corvane's camp and journal", "the back of the Deep Door to the east", "the way down to the tomb in the north"],
      npcs: ["npc_corvane", "npc_tam"],
      secrets: ["t_corvane_daughter", "t_tam_below", "t_silver_given"],
      interactables: ["Corvane's journal", "a small painted portrait of a girl", "the empty niches"],
      encounters: ["e_hall_guard"],
      connected: ["loc_cairn", "loc_lower_mine", "loc_kings_tomb"],
      threats: ["the Lamplighter's dead"],
      discoverable: ["Corvane's journal", "Tam"],
    },
    {
      id: "loc_kings_tomb",
      name: "King Orrin's tomb",
      cells: [{ cx: 0, cy: -4, hint: "King Orrin's tomb: a round chamber, a stone bier, a crowned skeleton under a cold blue light" }],
      description: "A round chamber at the bottom of the barrow. King Orrin lies on a stone bier, crowned, under the Grave Lantern's cold light.",
      atmosphere: "Cold enough to see breath. The silence of something about to wake.",
      features: ["the bier", "the Ember Crown", "an inscription around the bier", "steps down from the halls"],
      npcs: ["npc_orrin"],
      secrets: ["t_crown_price"],
      interactables: ["the inscription", "the crown", "the Grave Lantern, if Corvane is here"],
      encounters: ["e_tomb_fight", "e_corvane_talk"],
      connected: ["loc_barrow_halls"],
      threats: ["Corvane's last guard", "the king, if he wakes"],
      discoverable: ["the inscription", "what the crown does"],
    },
  ],

  acts: [
    {
      id: "act_something_wrong",
      title: "Act I: Something Is Wrong in Blackstone",
      goal: "Find out what happened to the three missing villagers.",
      conflict:
        "The village blames the goblins, the mayor wants it to stay that way, and the goblins really did take two of them, for a reason nobody in the village will say out loud.",
      locations: ["loc_square", "loc_mayors_house", "loc_shrine", "loc_carters_yard", "loc_mine_road", "loc_goblin_camp", "loc_upper_mine"],
      npcs: ["npc_venn", "npc_hobb", "npc_wenna", "npc_pell", "npc_grukka", "npc_snik"],
      revelation: "The goblins are not the threat. The mayor broke the village's oath, and the thing the goblins have guarded for generations is waking.",
      advanceWhen: { allOf: ["b_mayor_involved", "b_something_below"] },
      transition:
        "The player knows the mayor broke the oath and that something under the ridge is stirring. Blackstone's problem has become the valley's: whoever is buying the silver, and whatever is behind the Deep Door, are the story now. Let this act's people come to the player: Wenna is ready to talk, Pell is ready to be believed, and Grukka wants a word.",
      beats: [
        {
          id: "b_mayor_involved",
          text: "The player discovers the mayor is involved.",
          required: "Evidence connecting the mayor to the unpaid toll or to the silver.",
          canHappenThrough: ["the tithe ledger", "the buyer's letters", "Grukka's testimony", "Wenna's crates", "the mayor confessing under pressure", "the picks in the lower mine"],
          notBefore: { anyOf: ["evidence_against_mayor", "t_grain_toll", "cl_wennas_crates"] },
          result: "The mayor becomes suspicious of the player and starts burning what he can.",
        },
        {
          id: "b_something_below",
          text: "The player learns that something under the ridge is waking.",
          required: "Any real sign of the dead or of the Deep Door.",
          canHappenThrough: ["Hobb's account", "the scratching below the mine", "the oath stone", "Grukka", "Sexton Pell", "seeing the ridge walkers"],
          notBefore: { anyOf: ["cl_hobbs_account", "cl_scratching", "cl_oath_stone", "t_dead_walk_ridge", "t_oath_seal", "c_ridge_walkers"] },
          result: "The story widens from a village problem to something under the ridge.",
        },
        {
          id: "b_pell_heard",
          text: "Someone finally listens to Sexton Pell.",
          required: "The player visits the shrine and takes Pell seriously.",
          canHappenThrough: ["asking her about the goblins", "asking about the ridge", "bringing her evidence", "Hobb sending them to her", "helping her with something small first"],
          result: "Pell begins to trust the player. She gives them the old terms of the oath now, and the bell's rite whenever they need it.",
          sets: ["pell_trusts_player"],
        },
      ],
      arcs: [
        {
          id: "a_missing_three",
          name: "The Missing Three",
          purpose: "Pull the player into the village's problem and let them find the first loose thread.",
          startingState: "Three people missing, notices on the board, a mayor blaming goblins and offering a reward, and a watchman who found tracks and was told to ignore them.",
          objective: "Find out where the missing went.",
          conflict: "The mayor steers everyone toward the goblins and away from his ledgers; Wenna is too frightened to talk; Hobb is loyal to the mayor; nobody listens to Pell.",
          npcs: ["npc_venn", "npc_hobb", "npc_wenna", "npc_pell"],
          locations: ["loc_square", "loc_mayors_house", "loc_carters_yard", "loc_shrine", "loc_mine_road"],
          clues: [
            {
              id: "cl_tracks",
              text: "Bare goblin footprints and drag marks leading from the mill to the old mine road, two weeks old, and a fresher set: one pair of boy's boots walking alone, uphill, toward the mine.",
              source: "the old mine road north of the square",
              pointsTo: ["t_goblins_took_two", "t_tam_below"],
            },
            {
              id: "cl_tithe_ledger",
              text: "The village tithe ledger: a grain payment to 'the Teeth' every season for ninety years, in a dozen different hands, stopping three months ago in the mayor's.",
              source: "the shelf in the mayor's study, in plain sight",
              pointsTo: ["t_grain_toll"],
              sets: ["evidence_against_mayor"],
            },
            {
              id: "cl_buyer_letters",
              text: "Letters to the mayor in a fine scholar's hand ordering 'grave-silver, as before', promising payment at the cairn, each signed with a small drawn lantern.",
              source: "the mayor's locked desk",
              pointsTo: ["t_mayor_selling_silver", "t_lantern_mark"],
              sets: ["evidence_against_mayor"],
            },
            {
              id: "cl_hobbs_account",
              text: "Hobb has seen two skeletons walking the ridge at dusk, twice, and the mayor told him to stop talking about ghosts.",
              source: "Hobb, once he trusts the player or is caught alone",
              pointsTo: ["t_dead_walk_ridge"],
            },
            {
              id: "cl_wennas_crates",
              text: "Wenna has hauled six sealed, heavy crates from the mine to the cairn at night for the mayor, and Tam asked what was in them the day before he vanished.",
              source: "Wenna, if the player promises to look for Tam or presses her kindly",
              pointsTo: ["t_mayor_selling_silver", "t_tam_below"],
            },
            {
              id: "cl_bell_inscription",
              text: "Tiny letters around the rim of the Quiet Bell: 'Rung below, he sleeps.'",
              source: "the Quiet Bell in the shrine",
              pointsTo: ["t_bell_rite"],
            },
          ],
          approaches: [
            "question the villagers, Hobb and Wenna",
            "search the mayor's study, openly or by night",
            "follow the tracks up the mine road",
            "ask Sexton Pell, whom everyone else ignores",
            "go straight to the goblins",
            "take the mayor's commission and see where it leads",
          ],
          outcomes: [
            {
              id: "o_mayor_exposed",
              text: "The player exposes the mayor in front of the village, with evidence.",
              sets: ["mayor_exposed"],
              attitudes: [
                { id: "npc_venn", attitude: "hostile" },
                { id: "f_village", attitude: "friendly" },
              ],
            },
            {
              id: "o_mayor_confessed",
              text: "The player confronts the mayor in private and he confesses, begging them to keep it quiet.",
              sets: ["mayor_confessed"],
              attitudes: [{ id: "npc_venn", attitude: "unfriendly" }],
            },
            {
              id: "o_mayor_covered",
              text: "The player agrees to help the mayor keep it quiet.",
              sets: ["mayor_ally"],
              attitudes: [
                { id: "npc_venn", attitude: "allied" },
                { id: "npc_pell", attitude: "unfriendly" },
              ],
            },
            {
              id: "o_village_left",
              text: "The player walks away from the village's problem.",
              sets: ["village_abandoned"],
              attitudes: [{ id: "f_village", attitude: "unfriendly" }],
            },
          ],
          rewards: ["Hobb's trust and his spear beside the player", "Wenna's trust", "a village that will listen to the player instead of the mayor"],
          failure: "If the player never pulls the thread, the village raids the goblin camp on its own, and this arc resolves itself badly.",
          worldChanges: ["the mayor's standing in the village", "whether Blackstone listens to the player or to the mayor"],
          scenes: [
            {
              id: "s_notice_board",
              name: "The notice board",
              location: "loc_square",
              situation: "The mayor is reading Tam Holt's name off a fresh notice to an angry crowd and promising a reward for goblin ears.",
              npcsPresent: ["npc_venn", "npc_hobb", "npc_wenna"],
              whatTheyWant: "Venn wants a hero who will go and fight goblins. Hobb wants to be told what to do. Wenna wants everyone to stop talking and start looking.",
              playerKnows: "Three people are missing and the village blames goblins.",
              hidden: "Venn's hands shake whenever someone mentions the mine. Wenna will not look at him.",
              interactions: ["read the notices", "talk to the crowd", "question the mayor", "talk to Hobb", "watch Wenna"],
              checks: [
                { skill: "Insight", dc: 12, reveals: "the mayor is frightened of something other than goblins" },
                { skill: "Insight", dc: 12, reveals: "Wenna is hiding something, and hates the mayor for it" },
              ],
              escalation: "If the player sides loudly with the goblins, the crowd turns ugly and Venn has Hobb walk them out of the square.",
              outcomes: ["the player takes the mayor's commission", "the player starts asking their own questions"],
            },
            {
              id: "s_mayors_study",
              name: "The mayor's study",
              location: "loc_mayors_house",
              situation: "A cold, tidy room above the hall: ledgers on the shelf, a locked desk, a cold hearth full of burnt paper.",
              npcsPresent: ["npc_venn"],
              whatTheyWant: "Venn wants the player out of his study, politely if possible.",
              playerKnows: "The mayor keeps the village's records here.",
              hidden: "The tithe ledger on the shelf; the buyer's letters in the desk; a burnt corner of an older letter in the hearth with the lantern mark still on it.",
              interactions: ["search the shelves", "pick or force the desk", "sift the hearth", "talk the mayor round", "come back at night"],
              checks: [
                { skill: "Investigation", dc: 10, reveals: "the tithe ledger and the date the payments stop" },
                { skill: "Sleight of Hand", dc: 13, reveals: "the desk lock opens" },
                { skill: "Investigation", dc: 15, reveals: "the desk key, tucked under the drawer" },
                { skill: "Investigation", dc: 12, reveals: "the lantern mark on the burnt corner" },
              ],
              escalation: "If the player is caught, Venn calls for Hobb and tries to have them run out of the village, and burns the letters that night unless someone stops him.",
              outcomes: ["the player finds the evidence", "the player is caught and thrown out", "the player talks Venn into showing them"],
            },
            {
              id: "s_carters_yard",
              name: "Wenna's yard",
              location: "loc_carters_yard",
              situation: "Wenna is loading an empty cart with nothing, to keep her hands busy. Tam's coat is still on its peg.",
              npcsPresent: ["npc_wenna"],
              whatTheyWant: "Wenna wants Tam back, and is terrified that the crates are why he is gone.",
              playerKnows: "Her son is one of the missing.",
              hidden: "The crates, the cairn, and Tam's questions.",
              interactions: ["offer to find Tam", "ask about her work", "look over the cart", "ask about the mayor"],
              checks: [
                { skill: "Insight", dc: 12, reveals: "she is hiding something about her work" },
                { skill: "Investigation", dc: 11, reveals: "grey silver dust in the cart bed, and a lantern scratched into one board" },
              ],
              escalation: "If pressed hard or threatened, she shuts the gate on the player and goes to warn the mayor.",
              outcomes: ["Wenna tells the player about the crates", "Wenna sends the player away"],
            },
            {
              id: "s_shrine",
              name: "The Quiet Bell",
              location: "loc_shrine",
              situation: "Sexton Pell is sweeping a floor that is already clean, under a small bronze bell nobody looks at.",
              npcsPresent: ["npc_pell"],
              whatTheyWant: "Pell wants someone to believe her: the goblins are not the enemy, and the bell was not hung there to be looked at.",
              playerKnows: "There is a shrine and an old woman nobody listens to.",
              hidden: "Pell knows the old oath, the king's name and the bell's rite. She gives the oath to anyone who listens, and the rite only to someone she trusts.",
              interactions: ["ask about the bell", "ask about the goblins", "ask about the ridge", "help her with something small first", "read the bell's inscription"],
              checks: [
                { skill: "Religion", dc: 13, reveals: "the bell's inscription" },
                { skill: "Insight", dc: 10, reveals: "she is frightened, not mad" },
              ],
              escalation: "If mocked or hurried, Pell shuts the shrine door, and opens it again only to someone Hobb or Wenna vouches for.",
              outcomes: ["Pell is heard", "Pell is dismissed"],
            },
          ],
          encounters: [
            {
              id: "e_crowd",
              name: "The angry square",
              type: "social",
              difficulty: "easy",
              location: "loc_square",
              participants: ["Mayor Venn", "Hobb", "a dozen frightened villagers"],
              environment: "The square at dusk: torches, the well, the notice board.",
              objective: "Keep the village from marching on the goblins.",
              special: ["the crowd follows whoever sounds most certain"],
              npcBehavior: "Venn pushes for a raid. Hobb hesitates. Wenna says nothing.",
              triggers: ["the player speaks up in the square", "the ridge walkers are seen"],
              success: "The village waits for the player to look into it.",
              failure: "A raid party of a dozen villagers sets out for the mine at dawn.",
              alternatives: ["calm them (Persuasion DC 13)", "shout them down (Intimidation DC 13)", "show them evidence against the mayor"],
              rewards: ["the village's patience", "Hobb's respect"],
            },
          ],
        },
        {
          id: "a_hollow_teeth",
          name: "The Hollow Teeth",
          purpose: "Turn 'the goblins did it' into 'the goblins did it, and here is why', and introduce what is under the mine.",
          startingState:
            "The Hollow Teeth hold Bessa and Jory in their camp at the mine mouth. Snik wants to raid the village for the unpaid grain. Grukka is holding him back, barely.",
          objective: "Get the captives back.",
          conflict:
            "The goblins want the toll; the village will not pay; Snik wants blood; and the warriors are on edge because something has been scratching at the Deep Door from the far side.",
          npcs: ["npc_grukka", "npc_snik"],
          locations: ["loc_mine_road", "loc_goblin_camp", "loc_upper_mine"],
          clues: [
            {
              id: "cl_goblin_testimony",
              text: "Grukka's account: the village paid grain for ninety years for the goblins to guard the bottom of the mine; the mayor stopped paying and sent men to dig silver down there instead; a village boy went down the shaft alone and did not come back.",
              source: "Grukka, if the player talks before fighting",
              pointsTo: ["t_grain_toll", "t_mayor_selling_silver", "t_tam_below"],
              sets: ["evidence_against_mayor"],
            },
            {
              id: "cl_scratching",
              text: "Scratching from below at night, from the far side of the stone the goblins guard, and a cold that comes up the shaft.",
              source: "the upper workings, listened to after dark",
              pointsTo: ["t_oath_seal", "t_dead_walk_ridge"],
            },
            {
              id: "cl_oath_stone",
              text: "A carved stone at the camp's heart: a bell, a goblin hand and a human hand clasped, and a crowned figure lying down beneath them.",
              source: "the oath stone in the goblin camp",
              pointsTo: ["t_oath_seal"],
            },
          ],
          approaches: [
            "parley with Grukka",
            "pay the grain toll from their own pocket or the village's",
            "sneak in and free the captives",
            "fight their way in",
            "face Snik alone and shame him",
            "bring Sexton Pell, whom Grukka respects",
          ],
          outcomes: [
            {
              id: "o_captives_negotiated",
              text: "The player negotiates Bessa and Jory's release, on a promise that the toll will be paid.",
              sets: ["captives_freed", "goblin_deal"],
              attitudes: [
                { id: "f_hollow_teeth", attitude: "friendly" },
                { id: "npc_grukka", attitude: "friendly" },
              ],
            },
            {
              id: "o_captives_stolen",
              text: "The player frees the captives without the goblins' consent.",
              sets: ["captives_freed"],
              attitudes: [{ id: "f_hollow_teeth", attitude: "unfriendly" }],
            },
            {
              id: "o_goblins_fought",
              text: "The player fights the Hollow Teeth and takes the captives by force.",
              sets: ["captives_freed", "goblins_bloodied"],
              attitudes: [
                { id: "f_hollow_teeth", attitude: "hostile" },
                { id: "npc_grukka", attitude: "hostile" },
              ],
            },
            {
              id: "o_goblins_allied",
              text: "The player swears to see the oath honoured, and the Hollow Teeth agree to stand with them against what is below.",
              sets: ["captives_freed", "goblin_deal", "goblin_alliance"],
              attitudes: [
                { id: "f_hollow_teeth", attitude: "allied" },
                { id: "npc_grukka", attitude: "allied" },
              ],
            },
          ],
          rewards: ["the captives home safe and the village grateful", "Grukka's knowledge of the mine", "goblin guides down the shaft, if allied"],
          failure: "If the player does nothing, Snik leads a raid on the village within days, someone dies on each side, and the village marches on the camp in return.",
          worldChanges: ["whether the goblins keep guarding the Deep Door, help the player, or flee", "whether the village owes the goblins or hates them"],
          scenes: [
            {
              id: "s_mine_mouth",
              name: "The mine mouth",
              location: "loc_goblin_camp",
              situation:
                "A camp of hide tents and mine timbers at the mouth of the mine. Two goblin sentries see the player coming long before the player sees them. Bessa and Jory sit roped under an awning, fed and bored.",
              npcsPresent: ["npc_grukka", "npc_snik"],
              whatTheyWant: "Grukka wants the toll, and to know whether the player speaks for the village. Snik wants an excuse.",
              playerKnows: "Goblins live here; the missing might be here.",
              hidden: "The goblins are frightened, and not of the player. Half the warriors sleep facing the mine.",
              interactions: ["call out and parley", "creep in", "watch the camp", "challenge Snik", "show the oath stone respect"],
              checks: [
                { skill: "Stealth", dc: 13, reveals: "getting close unseen" },
                { skill: "Persuasion", dc: 13, reveals: "Grukka talks instead of fighting" },
                { skill: "Insight", dc: 11, reveals: "the goblins keep glancing at the mine, not at the player" },
              ],
              combat: "e_camp_fight",
              escalation: "If the player draws a weapon or is caught creeping, Snik attacks with one warrior and Grukka lets him, to see what the player is made of.",
              outcomes: ["a deal", "a rescue", "a fight"],
            },
            {
              id: "s_listening_shaft",
              name: "The listening shaft",
              location: "loc_upper_mine",
              situation: "The head of the mine shaft at night. Goblins sit around it in silence, listening.",
              npcsPresent: [],
              whatTheyWant: "The goblins want the scratching to stop, and do not want to be the ones who go down.",
              playerKnows: "Goblins guard this mine.",
              hidden: "The scratching is the dead, working at the Deep Door from the barrow side.",
              interactions: ["listen", "ask the goblins", "climb down"],
              checks: [{ skill: "Perception", dc: 12, reveals: "the scratching is fingers on stone, and there is more than one set" }],
              escalation: "If the player climbs down alone, the goblins do not stop them, and do not follow.",
              outcomes: ["the player hears it and comes away", "the player goes down to the Deep Door"],
            },
          ],
          encounters: [
            {
              id: "e_scout",
              name: "The lookout in the pines",
              type: "exploration",
              difficulty: "easy",
              location: "loc_mine_road",
              participants: ["one goblin scout in a tree"],
              environment: "Pine woods either side of a rutted road; the scout's platform is ten feet up.",
              objective: "Get up the road without the camp being warned, or catch the scout.",
              special: ["the scout runs rather than fights", "if it gets away, the camp is ready and Snik is waiting"],
              enemyBehavior: "Watches, then flees uphill to warn the camp. Fights only if cornered.",
              triggers: ["the player walks up the mine road"],
              success: "The player reaches the camp unexpected, or with a scout who can be talked to.",
              failure: "The camp knows the player is coming.",
              alternatives: ["spot it first (Perception DC 12)", "sneak past (Stealth DC 12)", "call up to it and talk"],
              rewards: ["surprise", "a frightened goblin willing to say why the clan took the captives"],
            },
            {
              id: "e_parley",
              name: "Parley at the mine mouth",
              type: "social",
              difficulty: "medium",
              location: "loc_goblin_camp",
              participants: ["Grukka Two-Knives", "Snik", "a ring of goblins"],
              environment: "The cook fire, the oath stone, the dark mouth of the mine behind.",
              objective: "Free the captives without a fight.",
              special: ["Grukka never bluffs and respects anyone who does not either", "a lie Grukka catches (Insight against the player's Deception) ends the parley"],
              npcBehavior: "Grukka states her terms plainly: the toll, or something worth the toll. Snik heckles.",
              triggers: ["the player approaches openly"],
              success: "Bessa and Jory walk home, and Grukka tells the player what the mayor did.",
              failure: "Grukka sends the player away with the captives still held, and Snik follows to see where they go.",
              alternatives: ["pay the toll", "promise to make the village pay", "offer to deal with what is scratching below", "bring Pell"],
              rewards: ["the captives", "Grukka's testimony", "goblin guides"],
            },
            {
              id: "e_camp_fight",
              name: "Snik's ambush",
              type: "combat",
              difficulty: "medium",
              location: "loc_goblin_camp",
              participants: ["Snik (a goblin)", "one goblin warrior, or two if the player is level 2 or higher"],
              environment: "Tents, guy-ropes and a fire pit; the mine mouth gives cover.",
              objective: "Survive, and get the captives out.",
              special: ["Grukka does not fight unless the player kills a goblin, and then she does", "if Snik goes down, the other goblins stop and look to Grukka"],
              enemyBehavior: "Snik fights to prove himself and wants a duel. The warrior hangs back and runs if hurt.",
              triggers: ["the player attacks", "Snik is provoked", "the player is caught freeing the captives"],
              success: "The goblins yield and the captives are freed.",
              failure: "If the player goes down and lives, they wake roped beside Bessa and Jory, with Grukka waiting to talk.",
              alternatives: ["yield and talk", "grab the captives and run"],
              rewards: ["the captives", "the goblins' fear instead of their respect"],
            },
          ],
        },
      ],
    },
    {
      id: "act_silver_road",
      title: "Act II: The Silver Road",
      goal: "Find out who is buying the grave-silver, and what is behind the Deep Door.",
      conflict: "The buyer hides behind the dead, the mayor is desperate, the Deep Door is giving way, and Tam Holt is somewhere under the ridge.",
      locations: ["loc_carters_yard", "loc_barrow_field", "loc_cairn", "loc_upper_mine", "loc_lower_mine", "loc_shrine"],
      npcs: ["npc_wenna", "npc_venn", "npc_pell", "npc_grukka", "npc_hobb", "npc_corvane"],
      revelation: "The buyer is Corvane Ash, the Lamplighter, and he is waking the king under the ridge.",
      advanceWhen: { allOf: ["b_lamplighter_named", "b_barrow_entered"] },
      transition:
        "The player knows who the Lamplighter is and has found a way into the barrow. Whatever they decided about the mayor and the goblins, the rest plays out under the ridge. Corvane knows someone is coming; the dead are thicker and less patient from here.",
      beats: [
        {
          id: "b_lamplighter_named",
          text: "The player learns who the buyer is.",
          required: "Something that names Corvane Ash or marks him unmistakably.",
          canHappenThrough: ["the archive seal", "meeting him at the cairn", "following the blue light", "Pell recognising the description", "Tam, if he is found early"],
          notBefore: { anyOf: ["cl_archive_seal", "cl_blue_light", "o_buyer_met", "t_corvane_is_buyer"] },
          result: "Corvane learns that someone knows his name, and the dead begin to watch the village at night.",
        },
        {
          id: "b_barrow_entered",
          text: "The player finds the way into the barrow halls.",
          required: "A way in: the dug-open barrow mouth behind the cairn, or the gap at the Deep Door.",
          canHappenThrough: ["searching the cairn by day", "following the dead back from the cairn", "squeezing through the gap at the Deep Door", "opening the Deep Door"],
          notBefore: { anyOf: ["barrow_way_found"] },
          result: "The way to the Lamplighter is open.",
        },
        {
          id: "b_tam_alive",
          text: "The player learns that Tam is alive.",
          required: "Real evidence that Tam is alive under the ridge.",
          canHappenThrough: ["Grukka's sentries", "the boot prints by the Deep Door", "a glimpse of a boy with a lantern pole at the cairn", "the boot print behind the cairn"],
          result: "Wenna's hope becomes the player's reason.",
        },
      ],
      arcs: [
        {
          id: "a_the_buyer",
          name: "The Buyer at the Cairn",
          purpose: "Put a name and a face to the lantern mark.",
          startingState: "The mayor's last crate of silver is due at the cairn. The buyer collects at midnight, and the dead walk the ridge while he does.",
          objective: "Find out who the buyer is.",
          conflict: "The buyer only comes at night, under the eyes of his dead, and the mayor will warn him if he can.",
          npcs: ["npc_wenna", "npc_venn", "npc_corvane", "npc_hobb"],
          locations: ["loc_carters_yard", "loc_barrow_field", "loc_cairn"],
          clues: [
            {
              id: "cl_archive_seal",
              text: "A wax seal on the payment purse: the crossed keys of the royal archive in the capital, scratched through.",
              source: "the payment niche in the cairn, or the purse in the mayor's desk",
              pointsTo: ["t_corvane_is_buyer"],
            },
            {
              id: "cl_blue_light",
              text: "A cold blue light moving among the barrows at night, and skeletons walking beside it like an honour guard.",
              source: "the barrow-field, watched after dark",
              pointsTo: ["t_corvane_is_buyer", "t_dead_walk_ridge"],
            },
            {
              id: "cl_cairn_tunnel",
              text: "Behind the cairn, a barrow mouth recently dug open, lantern soot on its lintel and a boy's boot print in the dust.",
              source: "the cairn, searched by day",
              pointsTo: ["t_tam_below"],
              sets: ["barrow_way_found"],
            },
          ],
          approaches: [
            "ride along on Wenna's last delivery",
            "stake out the cairn at night",
            "follow the dead back to their barrow",
            "make the mayor write to the buyer and set a trap",
            "search the cairn by day",
          ],
          outcomes: [
            {
              id: "o_buyer_met",
              text: "The player meets the Lamplighter at the cairn and learns his name.",
              sets: ["met_corvane"],
            },
            {
              id: "o_silver_cut_off",
              text: "The player stops the last silver reaching the buyer: the crate seized, the mayor stopped, or Wenna persuaded to refuse.",
              sets: ["silver_cut_off"],
              attitudes: [{ id: "npc_corvane", attitude: "unfriendly" }],
            },
            {
              id: "o_buyer_followed",
              text: "The player follows the dead back to their barrow.",
              sets: ["barrow_way_found"],
            },
          ],
          rewards: ["the villain's name", "the way into the barrow from the ridge", "Wenna's gratitude"],
          failure: "If the last silver reaches him, the lantern is finished on schedule.",
          worldChanges: ["whether Corvane knows the player is coming", "whether the lantern is finished on time"],
          scenes: [
            {
              id: "s_night_cairn",
              name: "The cairn at midnight",
              location: "loc_cairn",
              situation:
                "A tall stack of black stones at the top of the ridge, with Wenna's crate at its foot. At midnight a cold blue light comes up out of the barrow behind it, and with it a thin man and two skeletons.",
              npcsPresent: ["npc_corvane"],
              whatTheyWant: "Corvane wants the silver and no witnesses. He would rather talk than fight, and rather leave than talk.",
              playerKnows: "Someone collects the silver here at night.",
              hidden: "The skeletons obey the lantern, not Corvane: if the lantern goes out of their sight, they stop. Corvane himself is no fighter.",
              interactions: ["hide and watch", "step out and speak", "seize the crate", "go for the light", "follow him back"],
              checks: [
                { skill: "Stealth", dc: 13, reveals: "watching unseen" },
                { skill: "Arcana", dc: 13, reveals: "the dead move when the lantern moves" },
                { skill: "Persuasion", dc: 14, reveals: "Corvane stays and talks" },
              ],
              combat: "e_cairn_guard",
              escalation: "If threatened, Corvane steps back into the barrow and the two skeletons step forward.",
              outcomes: ["the player learns his name", "the player cuts off the silver", "the player follows him"],
            },
            {
              id: "s_ridge_at_dusk",
              name: "The ridge at dusk",
              location: "loc_barrow_field",
              situation: "The barrow-field as the light goes. Frost on the mounds, and footprints in it that are only bone.",
              npcsPresent: [],
              whatTheyWant: "The dead want to walk their circuit and go back down.",
              playerKnows: "People say something walks up here.",
              hidden: "The walkers come from the cairn and go back to it.",
              interactions: ["hide among the mounds", "follow the footprints", "wait for the light"],
              checks: [{ skill: "Survival", dc: 11, reveals: "the bone footprints all lead to and from the cairn" }],
              escalation: "If the player is seen, two skeletons come for them and stop at the first standing stone.",
              outcomes: ["the player sees the blue light", "the player finds where the dead go"],
            },
          ],
          encounters: [
            {
              id: "e_cairn_guard",
              name: "The lantern's guard",
              type: "combat",
              difficulty: "medium",
              location: "loc_cairn",
              participants: ["two skeletons, or one if the player is level 1"],
              environment: "A windy hilltop, grave mounds for cover, a steep drop on the east side.",
              objective: "Survive, or get past them to the light.",
              special: ["the skeletons stand still for a round whenever the lantern is out of their sight", "Corvane does not fight; he leaves"],
              enemyBehavior: "They put themselves between the player and the lantern and do not chase past the cairn.",
              triggers: ["the player threatens Corvane or the lantern", "the player is spotted"],
              success: "The dead fall, and the crate is the player's.",
              failure: "If the player goes down and lives, they wake at dawn on the hilltop with the crate gone and a small lantern drawn on the back of their hand in cold blue wax.",
              alternatives: ["talk", "hide", "grab the crate and run downhill"],
              rewards: ["the crate", "a sight of the barrow mouth Corvane retreats into"],
            },
          ],
        },
        {
          id: "a_deep_door",
          name: "The Deep Door",
          purpose: "Show the player what is under the mine, and give the goblins' oath its meaning.",
          startingState:
            "At the bottom of the mine the mayor's diggers broke into an old barrow tunnel next to the Deep Door, a round stone seal carved with a bell. The dead are working at it from the far side and have it nearly loose.",
          objective: "Find out what is behind the Deep Door, and keep it shut.",
          conflict: "The mine is dark, half flooded and full of the mayor's careless digging; the dead are pushing; and the goblins help only if the oath means something to the player.",
          npcs: ["npc_grukka", "npc_pell"],
          locations: ["loc_upper_mine", "loc_lower_mine"],
          clues: [
            {
              id: "cl_door_carvings",
              text: "Carvings around the Deep Door: a bell, a goblin hand and a human hand, and a crowned king lying down. Beneath them: 'Rung below, he sleeps. Lit above, he rises. Who wears it, keeps it, cold.'",
              source: "the Deep Door itself",
              pointsTo: ["t_oath_seal", "t_bell_rite", "t_crown_price"],
            },
            {
              id: "cl_fresh_digging",
              text: "Picks, a lantern from the mayor's hall and a ledger of silver weights, left in the breach where the miners broke into the barrow tunnel.",
              source: "the lower workings",
              pointsTo: ["t_mayor_selling_silver"],
              sets: ["evidence_against_mayor"],
            },
            {
              id: "cl_boy_prints",
              text: "A boy's boot prints going through the gap at the edge of the Deep Door, with bony footprints either side of them.",
              source: "the floor by the Deep Door",
              pointsTo: ["t_tam_below"],
              sets: ["barrow_way_found"],
            },
          ],
          approaches: ["go down with goblin guides", "go down alone", "bring Pell's reading of the carvings", "brace the door with timber and stone", "open it", "slip through the gap"],
          outcomes: [
            {
              id: "o_door_held",
              text: "The player, with the Hollow Teeth or alone, braces the Deep Door so the dead cannot push it open.",
              sets: ["deep_door_held"],
              attitudes: [{ id: "f_hollow_teeth", attitude: "friendly" }],
            },
            {
              id: "o_door_opened",
              text: "The player opens the Deep Door from the mine side.",
              sets: ["barrow_way_found", "door_opened_by_player"],
              attitudes: [{ id: "f_hollow_teeth", attitude: "unfriendly" }],
            },
            {
              id: "o_door_passed",
              text: "The player slips through the gap at the door's edge into the barrow halls.",
              sets: ["barrow_way_found"],
            },
          ],
          rewards: ["the way into the barrow from below", "the goblins' respect", "the carvings' warning about the crown"],
          failure: "If nobody braces it, the dead break the Deep Door on the villain's schedule.",
          worldChanges: ["whether the dead can come up through the mine", "whether the goblins keep their home"],
          scenes: [
            {
              id: "s_lower_workings",
              name: "The lower workings",
              location: "loc_lower_mine",
              situation:
                "Ladders down a cold shaft into ankle-deep water. Fresh pick marks where the mayor's men broke into an older, smoother tunnel. At its end, the round stone of the Deep Door, shifting slightly, with a hand's width of dark at its edge. Something on the other side is pushing.",
              npcsPresent: [],
              whatTheyWant: "The dead want the door open.",
              playerKnows: "There is a seal down here the goblins guard.",
              hidden: "The door is held only by its own weight now. Two skeletons are on the far side, working at it.",
              interactions: ["read the carvings", "brace the door", "look through the gap", "squeeze through", "listen"],
              checks: [
                { skill: "Religion", dc: 12, reveals: "the carvings, in full" },
                { skill: "Athletics", dc: 14, reveals: "the door braced alone (DC 10 with goblin help)" },
                { skill: "Perception", dc: 11, reveals: "two sets of bony fingers working at the gap" },
              ],
              combat: "e_door_breach",
              escalation: "If the player lingers without bracing it, the door grinds open a little more each turn, and then the skeletons come through.",
              outcomes: ["the door is held", "the door is opened", "the player goes through"],
            },
          ],
          encounters: [
            {
              id: "e_door_breach",
              name: "Through the gap",
              type: "combat",
              difficulty: "medium",
              location: "loc_lower_mine",
              participants: ["two skeletons"],
              environment: "A narrow tunnel, ankle-deep water, the door half open behind them.",
              objective: "Push them back and shut the door, or get past them.",
              special: ["only one skeleton at a time can come through the gap", "goblin allies, if any came, hold the shaft and fight beside the player"],
              enemyBehavior: "They come through one at a time, silently, and never retreat.",
              triggers: ["the door grinds open", "the player squeezes through"],
              success: "The door can be shut and braced.",
              failure: "If the player goes down and lives, the dead drag them through the gap, and they wake in the barrow halls beside a humming boy with a lantern pole.",
              alternatives: ["brace the door before they reach it", "retreat up the shaft and let the goblins hold it"],
              rewards: ["the door shut", "goblin respect"],
            },
          ],
        },
      ],
    },
    {
      id: "act_unburied_king",
      title: "Act III: The Unburied King",
      goal: "Stop the Ember Crown being lit, and bring Tam home.",
      conflict: "Corvane is down in the barrow with every dead thing on the ridge between him and the player, and his reason for all of it is one the player may not be able to argue with.",
      locations: ["loc_barrow_halls", "loc_kings_tomb", "loc_cairn", "loc_lower_mine", "loc_shrine"],
      npcs: ["npc_corvane", "npc_tam", "npc_orrin", "npc_pell", "npc_grukka"],
      revelation: "The crown cannot give Corvane what he wants, and whoever wears it becomes the next unburied king.",
      transition:
        "The player is going under the ridge. Corvane knows they are coming. The dead are thick in the halls, Tam carries the lantern pole, and the crown sits on a dead king's head waiting to be lit.",
      beats: [
        {
          id: "b_crown_truth",
          text: "The player learns what the crown really does.",
          required: "The inscription, the carvings, Tam, Pell, or the king himself.",
          canHappenThrough: ["the tomb inscription", "the Deep Door carvings", "Tam's half-woken words", "Sexton Pell", "King Orrin, if he wakes"],
          result: "The player has the one argument that might reach Corvane, and a reason never to put the crown on.",
        },
        {
          id: "b_face_to_face",
          text: "The player and Corvane talk, face to face, before it ends.",
          required: "A real conversation, however short, before the last fight or the last choice.",
          canHappenThrough: ["in the halls", "in the tomb", "at the cairn, if they never met before", "with a blade at his throat"],
          result: "Whatever happens next happens to a person, not a monster.",
        },
        {
          id: "b_its_over",
          text: "The confrontation in the tomb is over, one way or another.",
          required: "The tomb scene has settled: the lantern is out, the king sleeps, Corvane is stopped, or the crown is on someone's head, and the moment has passed.",
          canHappenThrough: ["the player walking out of the tomb", "the last enemy falling", "Corvane sitting down beside the bier", "the crown settling"],
          notBefore: { anyOf: ["corvane_stopped", "lantern_destroyed", "king_at_rest", "player_crowned"] },
          result: "The campaign reaches its ending.",
        },
      ],
      arcs: [
        {
          id: "a_barrow_halls",
          name: "The Barrow Halls",
          purpose: "The descent: dread, the dead, and Tam.",
          startingState: "Low stone halls lined with niches of bones, every third niche empty. Tam walks them with a lantern pole, lighting the way for the dead.",
          objective: "Reach the king's tomb, and free Tam if they can.",
          conflict: "The halls are full of the Lamplighter's dead, and Tam is under his hold.",
          npcs: ["npc_tam", "npc_corvane"],
          locations: ["loc_barrow_halls"],
          clues: [
            {
              id: "cl_corvane_journal",
              text: "Corvane's journal, on the coffin lid he uses as a desk: two years of entries addressed to 'my Lise', the last one reading 'Tonight, or the next. I will hear you laugh again.'",
              source: "Corvane's camp in the barrow halls",
              pointsTo: ["t_corvane_daughter", "t_silver_given"],
            },
            {
              id: "cl_tam_words",
              text: "Tam, half woken, whispering that the cold man talks to a little painted portrait every night, and that the crown 'is so cold, it makes him sad'.",
              source: "Tam, once his trance is broken or he is calmed",
              pointsTo: ["t_corvane_daughter", "t_crown_price"],
            },
          ],
          approaches: ["sneak through the halls", "fight through", "follow Tam, who walks to Corvane", "ring the Quiet Bell as they go, if they brought it", "come in from both sides with the goblins"],
          outcomes: [
            {
              id: "o_tam_freed",
              text: "Tam is woken from the trance and sent home, or brought along.",
              sets: ["tam_freed"],
              attitudes: [{ id: "npc_wenna", attitude: "allied" }],
            },
            {
              id: "o_tomb_reached",
              text: "The player reaches King Orrin's tomb.",
              sets: ["tomb_reached"],
            },
          ],
          rewards: ["Tam's life", "Wenna's gratitude for the rest of her days", "the truth about Corvane's grief"],
          failure: "If Tam is left under the hold, he stands beside Corvane at the end with the lantern pole, and the dead protect him.",
          worldChanges: ["whether Tam goes home"],
          scenes: [
            {
              id: "s_halls_of_niches",
              name: "The halls of niches",
              location: "loc_barrow_halls",
              situation: "A long, low hall with bones in niches on both sides. A boy walks slowly down the middle holding an unlit lantern pole, humming. Two skeletons walk behind him.",
              npcsPresent: ["npc_tam"],
              whatTheyWant: "Tam is walking to the tomb to light Corvane's way. The skeletons protect him.",
              playerKnows: "Tam is missing. This may be him.",
              hidden: "The trance breaks if he hears his mother's name and is shaken awake, if the Quiet Bell rings near him, or if the lantern goes out.",
              interactions: ["call to him", "follow him", "grab him", "deal with the skeletons", "hide"],
              checks: [
                { skill: "Persuasion", dc: 13, reveals: "Tam hears his mother's name and stops humming" },
                { skill: "Stealth", dc: 12, reveals: "following unseen to the tomb" },
                { skill: "Medicine", dc: 13, reveals: "the trance is not hurting him, and fear will not break it" },
              ],
              combat: "e_hall_guard",
              escalation: "If the player is seen, Tam keeps walking and the skeletons turn.",
              outcomes: ["Tam is freed", "Tam leads the player to Corvane"],
            },
          ],
          encounters: [
            {
              id: "e_hall_guard",
              name: "Tam's escort",
              type: "combat",
              difficulty: "medium",
              location: "loc_barrow_halls",
              participants: ["two skeletons"],
              environment: "A long low hall; the niches give cover and a place to hide; there is not room to swing a long weapon freely.",
              objective: "Get Tam away from them, or get past.",
              special: ["the skeletons never attack Tam", "if Tam's trance breaks, they ignore him and come for the player"],
              enemyBehavior: "They keep themselves between the player and the boy, and follow him if he walks on.",
              triggers: ["the player is seen", "the player grabs Tam"],
              success: "Tam is free, or the way to the tomb is clear.",
              failure: "If the player goes down and lives, they are carried to the tomb and laid at Corvane's feet, who apologises.",
              alternatives: ["break Tam's trance first", "sneak past and follow"],
              rewards: ["Tam", "the way to the tomb"],
            },
          ],
        },
        {
          id: "a_lamplighter",
          name: "The Lamplighter",
          purpose: "The confrontation, and the choice.",
          startingState: "King Orrin lies on his bier, crowned, under a cold blue light. Corvane kneels at its head with the Grave Lantern, reading the rite aloud. Two skeletons guard the steps.",
          objective: "Stop the crown being lit.",
          conflict: "Corvane will not stop for force alone, the dead will not stop while the lantern burns, and the crown offers the player the same thing it offers him.",
          npcs: ["npc_corvane", "npc_orrin", "npc_tam"],
          locations: ["loc_kings_tomb"],
          clues: [
            {
              id: "cl_tomb_inscription",
              text: "The inscription around Orrin's bier: 'The crown calls back the body and never the breath. Who wears it, keeps it, cold.'",
              source: "the bier in the king's tomb",
              pointsTo: ["t_crown_price"],
            },
          ],
          approaches: [
            "fight Corvane's guard and take the lantern",
            "smash or snuff the Grave Lantern",
            "ring the Quiet Bell over the king",
            "talk Corvane down with what the crown really does and what Lise would have wanted",
            "take the crown first",
            "let him finish, and face the king",
          ],
          outcomes: [
            {
              id: "o_corvane_let_go",
              text: "Corvane is talked out of it and puts the lantern out himself.",
              sets: ["corvane_stopped", "lantern_destroyed"],
              attitudes: [{ id: "npc_corvane", attitude: "friendly" }],
            },
            {
              id: "o_corvane_stopped",
              text: "Corvane is killed, captured or driven off.",
              sets: ["corvane_stopped"],
            },
            {
              id: "o_lantern_destroyed",
              text: "The Grave Lantern is smashed or snuffed, and the dead fall still.",
              sets: ["lantern_destroyed"],
            },
            {
              id: "o_king_at_rest",
              text: "The Quiet Bell rings in the tomb, and King Orrin sleeps again, for good.",
              sets: ["king_at_rest"],
            },
            {
              id: "o_player_crowned",
              text: "The player puts on the Ember Crown.",
              sets: ["player_crowned"],
            },
          ],
          rewards: ["Blackstone's future", "whatever Corvane leaves behind"],
          failure: "If the player flees the tomb, the clock runs on and the king wakes.",
          worldChanges: ["the ending"],
          scenes: [
            {
              id: "s_the_tomb",
              name: "The king's tomb",
              location: "loc_kings_tomb",
              situation: "Corvane kneels at the head of the bier, reading. The lantern burns blue beside him. Two skeletons stand on the steps. The crown on the dead king's head has begun, very faintly, to glow.",
              npcsPresent: ["npc_corvane", "npc_orrin"],
              whatTheyWant: "Corvane wants five more minutes. The dead want the rite finished.",
              playerKnows: "This is where it ends.",
              hidden: "Corvane already half suspects the crown cannot give him Lise. He has not let himself read the inscription on the bier.",
              interactions: ["speak to Corvane", "attack the guard", "go for the lantern", "ring the bell", "read the inscription aloud", "take the crown"],
              checks: [
                { skill: "Religion", dc: 12, reveals: "the inscription on the bier" },
                { skill: "Persuasion", dc: 18, reveals: "Corvane lets go; each piece of evidence the player shows him lowers this by 2" },
                { skill: "Sleight of Hand", dc: 13, reveals: "the lantern snuffed while he holds it" },
              ],
              combat: "e_tomb_fight",
              escalation: "Each turn the rite goes on, the crown glows brighter; if the player does nothing at all for several turns, the king's fingers move.",
              outcomes: ["Corvane lets go", "Corvane is stopped", "the lantern goes out", "the king sleeps", "the crown is taken"],
            },
          ],
          encounters: [
            {
              id: "e_tomb_fight",
              name: "The Lamplighter's last guard",
              type: "combat",
              difficulty: "hard",
              location: "loc_kings_tomb",
              participants: ["two skeletons", "Corvane Ash, who does not fight and holds the lantern"],
              environment: "A round chamber, steps down from the halls, the bier in the middle, cold enough to see breath.",
              objective: "Get to the lantern or the king, or stop Corvane.",
              special: [
                "while the lantern burns, one fallen skeleton stands up again at the start of the next round, once",
                "snuffing or smashing the lantern is a check, once the player is beside Corvane",
                "ringing the Quiet Bell takes an action and drops every skeleton where it stands",
              ],
              enemyBehavior: "The skeletons hold the steps and protect the lantern. Corvane keeps reading and backs away from violence.",
              npcBehavior: "Tam, if he is here and still entranced, holds up the lantern pole and does nothing else.",
              triggers: ["the player attacks", "the player goes for the lantern"],
              success: "The lantern is out or the guard is down, and Corvane is alone.",
              failure: "If the player goes down and lives, Corvane finishes the rite while they watch, and the king sits up.",
              alternatives: ["talk", "ring the bell", "read the inscription to him"],
              rewards: ["the end of it"],
            },
            {
              id: "e_corvane_talk",
              name: "Lise's father",
              type: "social",
              difficulty: "hard",
              location: "loc_kings_tomb",
              participants: ["Corvane Ash"],
              environment: "The tomb, the cold light, the crowned king between them.",
              objective: "Make him let go.",
              special: ["each true thing the player can show him (the journal, the inscription, Tam's words, Pell's account) makes him easier to reach"],
              npcBehavior: "He listens, because he was a scholar before he was anything else. He will not stop for threats.",
              triggers: ["the player speaks to him instead of attacking"],
              success: "He puts the lantern out himself, sits down beside the bier and weeps.",
              failure: "He turns back to the rite, and the skeletons step forward.",
              alternatives: ["fight", "ring the bell while he talks"],
              rewards: ["Corvane alive, and the lantern out"],
            },
          ],
        },
      ],
    },
  ],

  endings: [
    {
      id: "end_cold_crown",
      title: "The Cold Crown",
      when: { allOf: ["player_crowned", "b_its_over"] },
      text: "The crown is on the player's head and the dead kneel to them. Play the cold coming in: the power is real and the price has begun, and whoever is still near looks at them the way they once looked at Corvane. End on the player choosing what to command first.",
    },
    {
      id: "end_fallen",
      title: "The Unburied King",
      when: { allOf: ["c_king_wakes"] },
      text: "King Orrin is awake and crowned, and the dead are walking down the valley. Blackstone cannot be saved tonight. Play the flight from the village, let the player save whoever they can, and make it plain that the valley road belongs to the king now.",
    },
    {
      id: "end_dawn",
      title: "Dawn over Blackstone",
      when: { allOf: ["king_at_rest", "b_its_over"] },
      text: "The king sleeps for good, and the dead are still. Play the walk back out at dawn: who is waiting at the top of the ridge, what the village does with its mayor, what Grukka says about the oath, and whether Wenna gets her son back.",
    },
    {
      id: "end_quiet_ridge",
      title: "A Quiet Ridge",
      when: { allOf: ["b_its_over"] },
      text: "The lantern is out and the dead lie down, but King Orrin still wears his crown in an unsealed tomb. It is over for now. Play the return, and let the ridge feel unfinished: one day someone will light that crown again, unless the Quiet Bell is brought down to ring over him.",
    },
  ],

  dmNotes: [
    "Pitch every fight for one character between levels 1 and 3. Two goblins or two skeletons is a hard fight at level 1. Use the numbers each encounter gives, and drop one enemy when the player is level 1.",
    "Goblins take prisoners, and the Lamplighter's dead drag the fallen to their master: once the player is down, enemies in this campaign stop attacking them. The death saves are still the dice's.",
    "The goblins are not the threat. Let the player find that out; never tell them.",
    "Nobody here is simply evil. Venn is a frightened man doing a cowardly thing, Snik is a boy trying to be a warrior, and Corvane is a father. Let the player see it without excusing anyone.",
    "Dread at night, warmth by day. Daylight scenes in the village should feel like somewhere worth saving.",
    "Story objects (the tithe ledger, the buyer's letters, the Quiet Bell, Corvane's journal) are ordinary things, never magic items. When the player should be able to pocket one, put it on a prop with grantsItem as you build the room. When someone hands one over, record it in memoryFacts as an item.",
    "The villain's clock is the engine's. You never fire a step and you never announce one. When a STORY, OFFSCREEN note arrives, let the player meet it the way a person would: a rumour, a scream in the night, a door that was shut and is not.",
  ],
};
